### ISSUE TITLE
motion_picture titles not italicised, nor moved outside parentheses

### ISSUE THREAD

**Issue by nickbart1980** [jgm/pandoc-citeproc#118]
pandoc-citeproc does not render motion_picture titles as expected:
1) titles are enclosed in double quotes instead of being italicised (though the CSL file clearly instructs the processor to do the latter, see https://github.com/citation-style-language/styles/blob/master/chicago-author-date.csl#L197). This happens both in the in-text citation and the reference list entry.
2) Where the movie’s name appears in the text, it should appear before/outside of the parenthetical citation (containing the year only in such cases) – but it appears inside the parentheses.

Example (csl file is a patched chicago-author-date.csl which includes director as secondary-contributor, pull request submitted; but the original chicago-author-date.csl shows both issues as well, as does chicago-fullnote-bibliography.csl):

```
pandoc -F pandoc-citeproc -t markdown-citations << EOT

# Text
 
@nbn is a spy thriller film.

@item1 is a book, for comparison.

# References

---
csl: https://github.com/citation-style-language/styles/raw/ae2167dcb86db405b65915d2be591cf764a808b5/chicago-author-date.csl
references:
- type: motion_picture
  id: nbn
  title: North by Northwest
  director:
    family: Hitchcock
    given: Alfred
  issued:
    year: 1959
  publisher: Metro-Goldwyn-Mayer
  publisher-place: USA
  language: en-US

- title: Book title
  id: item1
  issued:
    year: 2013
  author:
    given: Al
    family: Author
  publisher: Publisher
  type: book
...
EOT
```
Expected output:

```
Text
====

*North by Northwest* (1959) is a spy thriller film.

Author (2013) is a book, for comparison.

<div class="references">

References {#references .unnumbered}
==========

<div id="ref-item1">

Author, Al. 2013. *Book Title*. Publisher.

</div>

<div id="ref-nbn">

*North by Northwest.* 1959. Directed by Alfred Hitchcock. USA:
Metro-Goldwyn-Mayer.

</div>

</div>
```

Actual output:

```
Text
====

(“North by Northwest” 1959) is a spy thriller film.

Author (2013) is a book, for comparison.

<div class="references">

References {#references .unnumbered}
==========

<div id="ref-item1">

Author, Al. 2013. *Book Title*. Publisher.

</div>

<div id="ref-nbn">

“North by Northwest.” 1959. Directed by Alfred Hitchcock. USA:
Metro-Goldwyn-Mayer.

</div>

</div>
```
