### ISSUE TITLE
Date ranges: "1–2. Marts 2011" instead of "1.–2. Marts 2011"

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#12]
It turns out that in CSL "a date can be rendered in either a localized or non-localized format." (http://citationstyles.org/downloads/specification.html#date)

chicago-author-date currently uses the non-localized format, which explains that while the month names are localized, the order of day and month, plus other elements, are not. I've been told a fix for this style is in the works.

chicago-fullnote-bibliography.csl does render dates in a localized format, and this seems to work well with pandoc, except for one issue concerning date ranges and localized versions of chicago-fullnote-bibliography.csl:

pandoc renders:

01–02. mart 2011 (Croatian)
1–2. Marts 2011 (Danish)
1–2. März 2011 (German)

Expected:

01.–02. mart 2011 (Croatian)
1.–2. Marts 2011 (Danish)
1.–2. März 2011 (German)

There's no problem if the range is not within the same month: E.g., "1. Marts–2. April 2011." (Danish)

Test:

```
pandoc --filter pandoc-citeproc -t markdown-citations <<EOT

Foo [@item1].

---
csl: chicago-fullnote-bibliography-da.csl
references:
- title: Title
  id: item1
  issued:
  - day: 1
    month: 03
    year: 2011
  - day: 2
    month: 03
    year: 2011
  author:
    given:
    - Ann
    family: Author
  container-title: Journal
  type: article-newspaper
...
EOT
```

```
$ diff -u chicago-fullnote-bibliography-da.csl chicago-fullnote-bibliography.csl 
--- chicago-fullnote-bibliography-da.csl    2013-12-20 08:38:56.000000000 +0100
+++ chicago-fullnote-bibliography.csl   2013-09-27 22:18:00.000000000 +0100
@@ -1,5 +1,5 @@
 <?xml version="1.0" encoding="utf-8"?>
-<style xmlns="http://purl.org/net/xbiblio/csl" class="note" version="1.0" demote-non-dropping-particle="never" default-locale="da-DK">
+<style xmlns="http://purl.org/net/xbiblio/csl" class="note" version="1.0" demote-non-dropping-particle="never">
   <info>
     <title>Chicago Manual of Style 16th edition (full note)</title>
     <id>http://www.zotero.org/styles/chicago-fullnote-bibliography</id>
```
