### ISSUE TITLE
Sorting in bibliography: lowercase appears after uppercase (“author” after “Zuthor”)

### ISSUE THREAD

**Issue by nickbart1980** [jgm/pandoc-citeproc#122]
This affects both lowercase family names and non-dropping-particles.

Example:

```
pandoc -s -F pandoc-citeproc -t markdown-citations-markdown_in_html_blocks << EOT
---
references:
- author:
  - family: author
    given: Al
  id: a
  issued:
    date-parts:
    - - 1985
  title: Title
  type: book

- author:
  - family: Author
    given: Al
  id: A
  issued:
    date-parts:
    - - 1985
  title: Title
  type: book

- author:
  - family: zuthor
    given: Zoe
  id: z
  issued:
    date-parts:
    - - 1985
  title: Title
  type: book

- author:
  - family: Zuthor
    given: Zoe
  id: Z
  issued:
    date-parts:
    - - 1985
  title: Title
  type: book

- author:
  - family: Doe
    given: Dan
    non-dropping-particle: de
  id: d
  issued:
    date-parts:
    - - 1985
  title: Title
  type: book
...

# Text

Foo [@A; @a; @d; @Z; @z].

# References

EOT
```

Expected:

```
Text
====

Foo (Author 1985; author 1985; de Doe 1985; Zuthor 1985; zuthor 1985).

References {#references .unnumbered}
==========

Author, Al. 1985. *Title*.

author, Al. 1985. *Title*.

de Doe, Dan. 1985. *Title*.

Zuthor, Zoe. 1985. *Title*.

zuthor, Zoe. 1985. *Title*.
```

Actual:

```
Text
====

Foo (Author 1985; author 1985; de Doe 1985; Zuthor 1985; zuthor 1985).

References {#references .unnumbered}
==========

Author, Al. 1985. *Title*.

Zuthor, Zoe. 1985. *Title*.

author, Al. 1985. *Title*.

de Doe, Dan. 1985. *Title*.

zuthor, Zoe. 1985. *Title*.
```

**Comment by jgm** [comment]
@nickbart1980 - I get the correct output for this test case (so I can't reproduce your "actual" output):
```
Text
====

Foo (Author 1985; author 1985; de Doe 1985; Zuthor 1985; zuthor 1985).

References {#references .unnumbered}
==========

Author, Al. 1985. *Title*.

author, Al. 1985. *Title*.

de Doe, Dan. 1985. *Title*.

Zuthor, Zoe. 1985. *Title*.

zuthor, Zoe. 1985. *Title*.
```
Are you perhaps using an older version inadvertently?

**Comment by nickbart1980** [comment]
No, latest dev version, but I'm usually compiling with `cabal install -ftest_citeproc -funicode_collation`. Without `-funicode_collation`, i.e., just `cabal install -ftest_citeproc`, I get the same result as you do.

**Comment by jgm** [comment]
I just installed with `-funicode_collation`.  Still couldn't reproduce what you're seeing...
With unicode_collation:
```
Text
====

Foo (Author [1985](#ref-A); author [1985](#ref-a); de Doe
[1985](#ref-d); Zuthor [1985](#ref-Z); zuthor [1985](#ref-z)).

References {#references .unnumbered}
==========

author, Al. 1985. *Title*.

Author, Al. 1985. *Title*.

de Doe, Dan. 1985. *Title*.

zuthor, Zoe. 1985. *Title*.

Zuthor, Zoe. 1985. *Title*.
```

**Comment by nickbart1980** [comment]
That's odd. I’m on MacOS 10.10, and have now upgraded to icu4c 55.1 (homebrew: https://homebrew.bintray.com/bottles/icu4c-55.1.yosemite.bottle.tar.gz), and reinstalled pandoc-citeproc (which in turn reinstalls text-icu-0.7.0.1) with the following:

```
pandoc-citeproc $ cabal install -ftest_citeproc -funicode_collation --extra-lib-dirs=/usr/local/opt/icu4c/lib --extra-include-dirs=/usr/local/opt/icu4c/include
Resolving dependencies...
In order, the following will be installed:
text-icu-0.7.0.1 (reinstall) changes: text-1.2.0.4 -> 1.1.0.0
pandoc-citeproc-0.7 +unicode_collation +test_citeproc (reinstall) changes:
aeson-pretty-0.7.2 added, attoparsec-0.11.3.4 added, process-1.2.0.0 added,
temporary-1.2.0.3 added, text-icu-0.7.0.1 added
Warning: Note that reinstalls are always dangerous. Continuing anyway...
Configuring text-icu-0.7.0.1...
Building text-icu-0.7.0.1...
Installed text-icu-0.7.0.1
Configuring pandoc-citeproc-0.7...
Building pandoc-citeproc-0.7...
Installed pandoc-citeproc-0.7
Updating documentation index
/Users/nick/Library/Haskell/share/doc/x86_64-osx-ghc-7.8.3/index.html
```

Output, as before:

```
Text
====

Foo (Author [1985](#ref-A); author [1985](#ref-a); de Doe
[1985](#ref-d); Zuthor [1985](#ref-Z); zuthor [1985](#ref-z)).

References {#references .unnumbered}
==========

Author, Al. 1985. *Title*.

Zuthor, Zoe. 1985. *Title*.

author, Al. 1985. *Title*.

de Doe, Dan. 1985. *Title*.

zuthor, Zoe. 1985. *Title*.
```

Anything else I could try?

**Comment by jgm** [comment]
I'm at a loss.  I've tried this with `-funicode_collation` on both Ubuntu linux and OSX (with icu4c installed via homebrew) , and in both cases I get correct sorting.  (I don't know if icu's collation is locale-dependent.  What is your locale?)

**Comment by nickbart1980** [comment]
Excellent guess. – `$locale` told me:

```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

Running

```
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
```

resolves the sorting issue, also for accented and other modified characters for which icu4c was originally brought in (see https://code.google.com/p/citeproc-hs/issues/detail?id=64).

Also, `export LC_ALL=da_DK.UTF-8; export LANG=da_DK.UTF-8` leads to the correct Danish sorting of “Ø” after “Z”, so this all looks ok.

My follow-up question is, could pandoc be patched to make icu4c use the locale matching the content of the `lang` variable, or, if this is empty, use en-US as a default?

**Comment by jgm** [comment]
+++ nickbart1980 [May 05 15 01:45 ]:
>Excellent guess. – `$locale` told me:
>
>```
>LANG=
>LC_COLLATE="C"
>LC_CTYPE="UTF-8"
>LC_MESSAGES="C"
>LC_MONETARY="C"
>LC_NUMERIC="C"
>LC_TIME="C"
>LC_ALL=
>```
>
>Running
>
>```
>export LC_ALL=en_US.UTF-8
>export LANG=en_US.UTF-8
>```
>
>resolves the sorting issue, also for accented and other modified characters for which icu4c was originally brought in (see https://code.google.com/p/citeproc-hs/issues/detail?id=64).
>
>Also, `export LC_ALL=da_DK.UTF-8; export LANG=da_DK.UTF-8` leads to the correct Danish sorting of “Ø” after “Z”, so this all looks ok.
>
>My follow-up question is, could pandoc be patched to make icu4c use the locale matching the content of the `lang` variable, or, if this is empty, use en-US as a default?

That should be possible.  Currently we have

    src/Text/CSL/Style.hs line 438:
          comp a b = T.collate (T.collator T.Current) (T.pack a) (T.pack b)

The `Current` means:  use the current locale.  Instead of `Current`, we
could use `Locale "en-US"` or whatever.

**Comment by jgm** [comment]
OK, on closer look, it's not easy to make the collation depend on the locale specified in the style.
The problem is that the `compare'` function, and the `Ord` instance it is used to define, doesn't have a parameter for style or locale.
I might try leaving it as Current and setting the LANG environment variable from within pandoc-citeproc, depending on the style.

**Comment by jgm** [comment]
That seems to work well.  The locale will be set by the `locale` metadata field, if present, and otherwise the style's own `default-locale`, or `en-US` if that isn't present either.

**Comment by nickbart1980** [comment]
Well, mostly. Locale-specific collation is not set from the `locale` metadata field yet.
I get the Danish collation, “Ø” after “Z”, only after running `export LC_ALL=da_DK.UTF-8` (interestingly enough, *not* with `export LC_COLLATE="da_DK.UTF-8"` alone).

**Comment by jgm** [comment]
Really?  It works for me:
```
---
locale: da_DK
references:
- issued:
  date-parts:
  - - 2005
  author:
  - given: John
    family: Øoe
  id: item1
  title: First book
  type: book
  publisher: Cambridge University Press
  publisher-place: Cambridge
- container-title: Journal of Generic Studies
  issued:
    date-parts:
    - - 2006
  author:
  - given: John
    family: Zoe
  id: item2
  title: Article
  type: article-journal
  volume: '6'
  page: '33-34'
...

@item1
@item2
``` 

With this I get Z before  Ø.
When I comment out the locale line in the metadata, I get Ø before Z.
