### ISSUE TITLE
pandoc-citeproc does not issue any warnings or errors for badly formatted YAML files.

### ISSUE THREAD

**Issue by DavidAntliff** [jgm/pandoc-citeproc#123]
External YAML files are supported by pandoc-citeproc (via both the --bibliography option and via inline YAML "bibliography: ") when pandoc-citeproc is invoked by pandoc. However there is no warning or error if the YAML input is not formatted correctly.

**Comment by jgm** [comment]
Please give an example, including the YAML you used, and the warning you would have expected to get.

**Comment by david-antliff-imgtec** [comment]
Apologies for the delay. I think the issue is that if the YAML file is not a valid YAML file (e.g. the initial --- marker is omitted, or there are other parsing issues - as opposed to data model issues which are another matter entirely) then it is silently accepted but ignored. Any unparsed references are then reported as missing: `pandoc-citeproc: reference XX not found`.

I encountered this issue with a large YAML bibliography that had some parsing errors, and it took me some time to work out where the issue was as all references were reported as missing with no clues as to why.

For example, this broken YAML file (the double dash for ref2 family is an error) will fail to satisfy either reference, even though the first one is parsable and there's no parse error displayed:

```
references:

- id: ref1
  title: 'Document 1'
  author:
  - family: Smith
    given: Paul
  issued:
    year: 2015
    month: 1
    day: 29

- id: ref2
  title: 'Document 2'
  author:
  -- family: Jones
    given: Roger
  issued:
    year: 2014
    month: 4
    day: 13

...
```

Errors are produced to say that the references are not found, but there's no YAML parser error to provide clues. In a large bibliography file, it's difficult to pinpoint the cause of the error.
