### ISSUE TITLE
Space after “al-”, “’s-”, etc. should be removed

### ISSUE THREAD

**Issue by nickbart1980** [jgm/pandoc-citeproc#129]
Example:

```
#!/bin/sh

cat > test.yaml  << EOT
---
references:
- id: hak
  type: article-journal
  author:
  - family: Ḥākim
    non-dropping-particle: al-
    given: Abu ‘Ali Mansur Tāriqu
  title: Title
- id: gra
  type: article-journal
  author:
  - family: Gravesande
    non-dropping-particle: ’s-
    given: Goverdus
  title: Title
- id: ale
  type: article-journal
  author:
  - family: Alembert
    non-dropping-particle: d’
    given: Jean Le Rond
  title: Title
...
EOT

pandoc -F pandoc-citeproc --biblio test.yaml -t markdown-citations-markdown_in_html_blocks << EOT

@hak @gra @ale

EOT
```

Actual output:

```
al- Ḥākim (n.d.) ’s- Gravesande (n.d.) d’Alembert (n.d.)

al- Ḥākim, Abu ‘Ali Mansur Tāriqu. n.d. “Title.”

d’Alembert, Jean Le Rond. n.d. “Title.”

’s- Gravesande, Goverdus. n.d. “Title.”
```

Expected output:

```
al-Ḥākim (n.d.) ’s-Gravesande (n.d.) d’Alembert (n.d.)

al-Ḥākim, Abu ‘Ali Mansur Tāriqu. n.d. “Title.”

d’Alembert, Jean Le Rond. n.d. “Title.”

’s-Gravesande, Goverdus. n.d. “Title.”
```

I’d assume that a space should be removed after *all* non-dropping particles that end with a hyphen – just as it is after particles that end with an apostrophe.

EDIT: Regarding the “no space after apostrophe” rule, note that there is at least one exception: after “de’” in “Lorenzo de’ Medici”, the space must be retained.
