### ISSUE TITLE
Excess trailing punctuation in cites in footnotes

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#13]
Using chicago-note-bibliography, titles wrapped in quotes are rendered with an excess trailing full stop when appearing at the end of a footnote.

[^1]: Author, “Title.”.

Expected:

[^1]: Author, “Title.”

Same effect seen with "Title?" and "Title!", and also in subsequent cites when using chicago-fullnote-bibliography.
No such effect in Zotero with either style.

Test:

```
pandoc --filter pandoc-citeproc -t markdown-citations <<EOT

Foo [@item1].

---
csl: chicago-note-bibliography.csl
references:
- title: Title
  id: item1
  issued:
  - year: 2011
  author:
    given:
    - Ann
    family: Author
  container-title: Journal
  type: article-newspaper
...
EOT

```
