### ISSUE TITLE
Parsing of two-field names with “al-”, “’s-”, etc. leaves family field empty

### ISSUE THREAD

**Issue by nickbart1980** [jgm/pandoc-citeproc#130]
Example:

```
#!/bin/sh
cat > test.yaml  << EOT
---
references:
- id: hak
  type: article-journal
  author:
  - family: al-Hakim
    given: Ahmad
  title: Title
- id: gra
  type: article-journal
  author:
  - family: ’s-Gravesande
    given: Goverdus
  title: Title
- id: deg2
  type: article-journal
  author:
  - family: de Gaulle
    given: Charles
  title: 'Title: Note non-breaking space betw. “de” and “Gaulle”'
...
EOT

pandoc-citeproc -y test.yaml
```

Actual output:

```
---
references:
- id: hak
  type: article-journal
  author:
  - given: Ahmad
    non-dropping-particle: al-Hakim
  title: Title

- id: gra
  type: article-journal
  author:
  - given: Goverdus
    non-dropping-particle: ’s-Gravesande
  title: Title

- id: deg2
  type: article-journal
  author:
  - given: Charles
    non-dropping-particle: de Gaulle
  title: 'Title: Note non-breaking space betw. “de” and “Gaulle”'
...
```

Expected output:

```
---
references:
- id: hak
  type: article-journal
  author:
  - family: Hakim
    given: Ahmad
    non-dropping-particle: al-
  title: Title

- id: gra
  type: article-journal
  author:
  - family: Gravesande
    given: Goverdus
    non-dropping-particle: ’s-
  title: Title

- id: deg2
  type: article-journal
  author:
  - family: de Gaulle
    given: Charles
  title: 'Title: Note non-breaking space betw. “de” and “Gaulle”'
...
```

EDIT (see below): ~~Over at citeproc-js, fbennett has implemented a somewhat more sophisticated approach to parsing two-name fields, apparently using a list of 80+ dropping and non-dropping particles. See discussion at https://forums.zotero.org/discussion/47161/names-reform-request-for-comments/, and relevant code at https://bitbucket.org/fbennett/citeproc-js/src/tip/src/util_name_particles.js?at=default.~~
