### ISSUE TITLE
Certain letters with diacritics mess up firstname–lastname order

### ISSUE THREAD

**Issue by nickbart1980** [jgm/pandoc-citeproc#134]
Certain letters with diacritics, at least ḫ (U+1E2B), ẖ (U+1E96), ḥ (U+1E25), mess up the firstname–lastname order of secondary contributors such as editors.

Zotero/LO does not show this effect.

Expected: `… Edited by Joe Faḫmy. …`

Actual: `… Edited by FaḫmyJoe. …`

Example:

```
pandoc -s -F pandoc-citeproc -t plain  << EOT
---
references:
- id: item1
  type: book
  author:
  - family: Doe
    given: John
  editor:
  - family: Faḫmy
    given: Joe
  issued:
  - year: 2015
  title: XXX
- id: item2
  type: book
  author:
  - family: Doe
    given: John
  editor:
  - family: Fahmy
    given: Joe
  issued:
  - year: 2015
  title: XXX
...

This shows the issue [@item1]. For comparison [@item2].

EOT
```
