### ISSUE TITLE
Titles as part of narrative need to be moved in front of parenthetical citation

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#136]
Where the title of a bibliographic item “appears in the text” (Chicago), or “is part of the narrative” (APA) instead of the author, whether dictated by necessity (anonymous works) or convention (movies), this title has to be moved outside of the parentheses.

Example: “_North by Northwest_ (1959) is a spy thriller film.” rather than “(_North by Northwest_ 1959) is a spy thriller film.”

See Chicago Manual of Style, 16e, 15.24; APA manual, 6e, 6.11; and discussions at https://groups.google.com/forum/?fromgroups&hl=en#!topic/pandoc-discuss/XxBP9rRLyVM and https://github.com/jgm/pandoc-citeproc/issues/118.

Example:

```
pandoc -F pandoc-citeproc -t plain << EOT

# Text

@nbn is a spy thriller film.

# References

---
csl: chicago-author-date.csl
references:
- id: nbn
  type: motion-picture
  director:
  - family: Hitchcock
    given: Alfred
  issued:
  - year: 1959
  title: North by Northwest
  publisher: Metro-Goldwyn-Mayer
  publisher-place: USA
  language: en-US
...

EOT
```

Actual output:

```
TEXT

(_North by Northwest_ 1959) is a spy thriller film.

REFERENCES

_North by Northwest_. 1959. Directed by Alfred Hitchcock. USA:
Metro-Goldwyn-Mayer.
```

Expected output:

```
TEXT

_North by Northwest_ (1959) is a spy thriller film.

REFERENCES

_North by Northwest_. 1959. Directed by Alfred Hitchcock. USA:
Metro-Goldwyn-Mayer.
```
