### ISSUE TITLE
Date disambiguation / multivolume monographs

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#14]
In the example below, including a multivolume monograph, one volume of the same multivolume monograph, and a chapter from one such volume, dates are incorrectly disambiguated as

Pelikan 1971a, Pelikan 1971, Pelikan 1971b

(Expected, of course: Pelikan 1971a, Pelikan 1971b, Pelikan 1971c)

What's more, changing `Foo [@CT, 12].` to `Foo [@CT, 1:12].` in the input below leads to complete loss of disambiguation:

Pelikan 1971, Pelikan 1971, Pelikan 1971

```
Foo (Pelikan 1971a, 12). Bar (Pelikan 1971, 1:12). Baz (Pelikan 1971b,
12).

<div class="references">

References
==========

Pelikan, Jaroslav. 1971a. *The Christian Tradition: A History of the
Development of Doctrine*. Chicago: University of Chicago Press.

———. 1971. *The Emergence of the Catholic Tradition (100–600)*. *The
Christian Tradition: A History of the Development of Doctrine*. Vol. 1.
Chicago: University of Chicago Press.

———. 1971b. “Chapter Two.” In *The Christian Tradition: A History of the
Development of Doctrine*, 1:34–56. Chicago: University of Chicago Press.

</div>
```

```
pandoc --filter pandoc-citeproc -t markdown-citations <<EOT

Foo [@CT, 12].
Bar [@CTv1, 12].
Baz [@CTv1c2, 12].

# References

---
csl: chicago-author-date.csl
references:
- title: Chapter two
  volume-title: The emergence of the Catholic tradition (100–600)
  volume: 1
  page: 34-56
  container-title: 'The Christian tradition: A history of the development of doctrine'
  id: CTv1c2
  issued:
  - year: 1971
  author:
    given: Jaroslav
    family: Pelikan
  publisher: University of Chicago Press
  publisher-place: Chicago
  type: chapter
  language: en-US

- container-title: 'The Christian tradition: A history of the development of doctrine'
  title: The emergence of the Catholic tradition (100–600)
  volume: 1
  id: CTv1
  issued:
  - year: 1971
  author:
    given: Jaroslav
    family: Pelikan
  publisher: University of Chicago Press
  publisher-place: Chicago
  type: book
  language: en-US

- title: 'The Christian tradition: A history of the development of doctrine'
  id: CT
  issued:
  - year: 1971
  author:
    given: Jaroslav
    family: Pelikan
  publisher: University of Chicago Press
  publisher-place: Chicago
  type: book
  language: en-US
...
EOT
```
