### ISSUE TITLE
References don’t work properly/use the full potential of AsciiDoc

### ISSUE THREAD

**Issue by and3k** [jgm/pandoc-citeproc#143]
test.md:

```

---
references:
- id: artcile
  title: Title
  issued:
    year: 2015
link-citations: true

---

Text [@artcile].

# References
```

```
pandoc test.md --filter pandoc-citeproc -t asciidoc
```

Output:

```
Text (“Title” link:#ref-artcile[2015]).

[[references]]
References
----------

“Title.” 2015.
```

Expected output:

```
Text <<ref-artcile>>.

[[references]]
References
----------

[bibliography]
- [[ref-artcile,(“Title” 2015)]]“Title.” 2015.
```

In AsciiDoc, citations are reference by `<<id>>`. And the citations are listed as `[[id,link-text-to-be-displayed]]Actual reference text`.

More on that:
- http://asciidoctor.org/docs/user-manual/#user-biblio
- http://www.methods.co.nz/asciidoc/userguide.html#_bibliography_lists

Thanks!
Bela
