### ISSUE TITLE
Bug in authorless citations when using pandoc and apa.csl

### ISSUE THREAD

**Issue by reagle** [jgm/pandoc-citeproc#152]
I'm not sure if this problem is in apa.csl or pandoc, but you'll note that when you run the command below on the attached test file you get an in-text citation that is broken: it only provides the title of the first citation ("Communities")---it needs both (and "Geek Feminism").

```
<p>I have two citations <span class="citation">(“Communities,” 2011, 2013)</span>.</p>
```

```
> pandoc --filter pandoc-citeproc -s --csl=apa.csl test.md -o test.html
```

pandoc 1.15.0.4
pandoc-citeproc 0.7.2

See [email](https://groups.google.com/forum/#!topic/pandoc-discuss/HbegcAWIbgo) for test files.

**Comment by jgm** [comment]
```
# Test

I have two citations [@Feminism2013gf; @Feminism2011ces].

# References

---
references:
- id: Feminism2013gf
  type: webpage
  container-title: "Geek Feminism"
  custom2: "ok.mm"
  issued:
    year: 2013
    month: 04
    day: 10
  keyword: "gender"
  title: "Geek Feminism"
  URL: "http://geekfeminism.wikia.com/wiki/Geek_Feminism"
  accessed:
    year: 2013
    month: 04
    day: 10
- id: Feminism2011ces
  type: entry-encyclopedia
  container-title: "Geek Feminism"
  custom2: "gender.mm"
  issued:
    year: 2011
    month: 08
    day: 14
  keyword: "gender"
  title: "Communities"
  URL: "http://geekfeminism.wikia.com/wiki/Category:Communities"
  accessed:
    year: 2011
    month: 10
    day: 19
...
```

with
```
pandoc --csl apa.csl -F pandoc-citeproc -t plain
```
yields
```
TEST


I have two citations (“Communities,” 2011, 2013).



REFERENCES


Communities. (2011, August 14). In _Geek Feminism_. Retrieved from
http://geekfeminism.wikia.com/wiki/Category:Communities

Geek Feminism. (2013, April 10). _Geek Feminism_. Retrieved April 10,
2013, from http://geekfeminism.wikia.com/wiki/Geek_Feminism
```
