### ISSUE TITLE
Empty no-author citation should not appear as ???

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc-citeproc#156]
No-author citation in modern-language-association.csl should not show up with ???.
In this case, output should be empty instead of ???.

```

---
title: 'Test Title'
author: Joseph Reagle
date: 20150611
csl: modern-language-association.csl
...

# Test

Raymond Williams [-@Williams1976kvc] argues Y as well.


# References

---
references:
- id: Williams1976kvc
  type: book
  publisher-place: "New York"
  author:
  - family: "Williams"
    given: "Raymond"
  custom1: "20140805"
  custom2: "fomo.mm"
  issued:
    year: 1976
  publisher: "Oxford University Press"
  title-short: "Keywords"
  title: "Keywords: A vocabulary of culture and society"
...
```

![screen shot 2015-08-08 at 10 53 26 am](https://cloud.githubusercontent.com/assets/3044/9151595/c286d9ca-3dbb-11e5-8d6c-66d0bb783b92.png)
