### ISSUE TITLE
Date range: March 1,–2, 2011 instead of March 1–2, 2011

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#18]
Probably introduced by the fix for https://github.com/jgm/pandoc-citeproc/issues/12 (at least I don't remember seeing this before):

```
pandoc --filter pandoc-citeproc -t markdown-citations <<EOT

Foo [@item1].

---
csl: chicago-fullnote-bibliography.csl
references:
- title: Title
  id: item1
  issued:
  - day: 1
    month: 03
    year: 2011
  - day: 2
    month: 03
    year: 2011
  author:
    given:
    - Ann
    family: Author
  container-title: Journal
  type: article-newspaper
...
EOT
```

Result:

```
Foo.[^1]

<div class="references">

Author, Ann. “Title.” *Journal*, March 1,–2, 2011.

</div>

[^1]: Ann Author, “Title,” *Journal*, March 1,–2, 2011.

```
