### ISSUE TITLE
Multiple Authors in BibLaTeX

### ISSUE THREAD

**Issue by MrLoh** [jgm/pandoc-citeproc#184]
I'm trying to cite a paper from two authros (pretty standard), but somehow the output is very weird. 

My entry is: 
```latex
@article{Copeland:1999at,
	title = {Alan Turing's forgotten ideas in Computer Science},
	author = {Copeland, B Jack {and} Proudfoot, Diane},
	journal = {Scientific American},
	pages = {99--103},
	year = {1999}
}
```

And in the text I get: 
> D. Copeland B Jack and Proudfoot 1999

And in the references: 
> Copeland, Diane, B Jack and Proudfoot. 1999. “Alan Turing’s Forgotten Ideas
in Computer Science.” *Scientific American*, 99–103.

I'm very confused what's going on and I simply can't find anything about this online, even though it seems to be the most standard problem you could possibly run into. Can anyone point me to how multiple authors ought to be formated correctly in BibLaTeX for panic-citeproc

**Comment by jgm** [comment]
Try removing the braces around "and".

+++ Tobias Lohse [Oct 20 15 14:59 ]:

**Comment by MrLoh** [comment]
That nearly solves it. In the citation I get: 
> Copeland and Proudfoot 1999

But in the references I still get: 
> Copeland, B Jack, and Diane Proudfoot. 1999. “Alan Turing’s Forgotten Ideas
in Computer Science.” *Scientific American*, 99–103.

Which is weird since the two authors are formated differently. Should be “and Proudfoot, Diane” without the coma before the and too I think. I guess that's a problem in my CSL. Any suggestions how to achieve that?

**Comment by MrLoh** [comment]
When I use `pandoc-citeproc --bib2yaml`

I get the correct output, which indicates that the chicago.csl creates the problem. 

```yaml
- id: Copeland:1999at
  type: article-journal
  author:
  - family: Copeland
    given: B Jack
  - family: Proudfoot
    given: Diane
  issued:
  - year: '1999'
  title: Alan turing’s forgotten ideas in computer science
  container-title: Scientific American
  page: '99-103'
```
