### ISSUE TITLE
Caps-protection in biblatex to CSL JSON/CSL YAML conversion

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#189]
It seems we got caps-protection in the biblatex to CSL JSON/CSL YAML conversion slightly wrong – or rather it turns out that there are undocumented (and highly counterintuitive!) differences between bibtex the program and biber/biblatex.

`{\emph{Foo}}` is parsed by biber/biblatex as emphasized but non-caps-protected string, and `\emph{Foo}` and `{{\emph{Foo}}}` as emphasized _and_ caps-protected strings, and apparently this _is_ the expected behavior: “This is just one of the small differences between bibtex the program and the btparse library used by biber.” (https://github.com/plk/biblatex/issues/357#issuecomment-154819866)

For a (xe)latex/biber/biblatex MWE demonstrating biber/biblatex’s actual behaviour, using biblatex-apa, a sentence-case style, see https://github.com/plk/biblatex/issues/357.

 `\textbf`, `\textsuperscript`, `\textsubscript`, `\enquote` and `\textsc` all show the same behaviour as `\emph`.

pandoc-citeproc currently converts

``` latex
@article{a,
  author       = {Doe, John},
  year         = {2015},
  title        = {Any {Foo} that appears uppercase is effectively protected
  – \emph{Foo}, {\emph{Foo}}, {{\emph{Foo}}}
  – \textbf{Foo}, {\textbf{Foo}}, {{\textbf{Foo}}}}
}
```

to

``` yaml

---
references:
- id: a
  type: article-journal
  author:
  - family: Doe
    given: John
  issued:
  - year: 2015
  title: Any Foo that appears uppercase is effectively protected – *foo*, *Foo*, *Foo*
    – **foo**, **Foo**, **Foo**
...
```

but should convert to

``` yaml

---
references:
- id: a
  type: article-journal
  author:
  - family: Doe
    given: John
  issued:
  - year: 2015
  title: Any Foo that appears uppercase is effectively protected – *Foo*, *foo*, *Foo*
    – **Foo**, **foo**, **Foo**
...
```

Note that this is about biblatex only, pandoc-citeproc’s bibtex to CSL JSON/CSL YAML converter should not be changed.
