### ISSUE TITLE
pandoc-citeproc drops the ‘dimensions’ variable

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#213]
pandoc-citeproc seems to silently ignore the CSL variable `dimensions`.

Example (using `harvard-university-of-kent.csl` as one of the official styles that supports `dimensions`):

```
pandoc -s -F pandoc-citeproc -t markdown-citations << EOT

Foo [@doe1].  

# References {-}

---
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/harvard-university-of-kent.csl
references:
- id: doe1
  type: book
  author:
  - family: Doe
    given: Ann
  issued:
  - year: '1999'
  title: Title
  collection-title: The collection title
  publisher: The publisher
  dimensions: '789 pp.'
...
EOT
```

Actual:

```
Foo (Doe 1999).

References {#references .unnumbered}
==========

<div id="refs" class="references">

<div id="ref-doe1">

Doe, A. (1999). *Title*. The collection title. The publisher.

</div>

</div>
```

Expected:

```
Foo (Doe 1999).

References {#references .unnumbered}
==========

<div id="refs" class="references">

<div id="ref-doe1">

Doe, A. (1999). *Title*. The collection title. The publisher. 789 pp.

</div>

</div>
```

Relevant section from `harvard-university-of-kent.csl`:

``` xml
<if type="book broadcast graphic legal_case motion_picture report song" match="any">
  <group prefix=" " delimiter=". " suffix=".">
    <text macro="title"/>
    <text macro="broadcast-info"/>
    <text macro="online"/>
    <group delimiter=" ">
      <text term="volume" form="short" text-case="capitalize-first"/>
      <text variable="volume"/>
    </group>
    <text macro="edition"/>
    <text macro="editor"/>
    <text variable="collection-title"/>
    <text variable="collection-number" prefix="Number "/>
    <text macro="publisher"/>
    <text variable="dimensions"/>
  </group>
</if>
```

Note that pandoc-citeproc renders `collection-title`, but not `dimensions`.
