### ISSUE TITLE
Incorrect handing of "et al" modifier

### ISSUE THREAD

**Issue by tlnagy** [jgm/pandoc-citeproc#27]
First of all, thank you for the wonderful project. It has greatly helped my workflow.

Now, I've noticed some non-standard behavior by pandoc when outputting citations using the standard [nature.csl](http://github.com/citation-style-language/styles/blob/master/nature.csl) and [science.csl](http://github.com/citation-style-language/styles/blob/master/science.csl) files (latest versions). I'm assuming this is pandoc-citeproc issue so I'm posting it here. 

It seems as though pandoc-citeproc is incorrectly interpreting the "et al" modifiers in the CSL language. So given the following file (bibtex version has the same problem):

```

---
references:
- issue: X
  page: XXXX-YYYY
  title: 'Sample Title'
  volume: XX
  id: AuthorOne2014
  issued:
    date-parts:
    - - 2014
  author:
  - given: Joe
    family: AuthorOne
  - given: Jill
    family: AuthorTwo
  container-title: Some Journal
  type: article-journal
csl: /[path to csl file]/science.csl

---
# Minimal example
Here is some text that needs a citation [@AuthorOne2014].
```

Results in the following bibliographic output (via `pandoc -s -F pandoc-citeproc`) 

```
1. J. AuthorOne, J. AuthorTwo et al., Sample Title, Some Journal XX, XXXX–YYYY (2014).
```

There _should not_ be an "et al" modifier after the author names. The correct output (using the exact same .csl file) generated with Mendeley:

```
1. J. AuthorOne, J. AuthorTwo, Sample Title, Some Journal XX, XXXX-YYYY (2014).
```

On the other hand, the [plos.csl](http://github.com/citation-style-language/styles/blob/master/plos.csl) file seems to behave correctly.

Version information:

```
pandoc-citeproc 0.3.0.1
pandoc 1.12.3
```

Please let me know if you need any more information to reproduce.
