### ISSUE TITLE
"mods2yaml": fix README, allow mods input to "pandoc-citeproc --bib2yaml / --bib2json"

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#28]
Right now there seems to be no direct way to convert MODS to CSL YAML or CSL JSON. The "mods2yaml" program mentioned in the README is no longer included with pandoc-citeproc.

Since pandoc-citeproc can read MODS and map its contents to CSL without problems, I wonder if `pandoc-citeproc --bib2yaml` and `pandoc-citeproc --bib2json` could be made to read MODS files, too, or, even better, all formats that bibutils is capable of converting to MODS (with the exception of .bib, .bibtex, and .json, of course, which pandoc-citeproc handles itself).

Interestingly, `pandoc-citeproc --bib2yaml article.ris` can read a ris file, and outputs yaml as expected (see article.ris below).

I also found that while `pandoc-citeproc --bib2yaml article.json` works almost as expected (though the backslashes it adds [e.g., `\\*Library Quarterly\\*`] will cause problems), `pandoc-citeproc --bib2json article.yaml` returns "Unknown format".

By the way, other citeprocs and database programs (Zotero, e.g.) don't understand the `*...*` emphasis and other markdown notation. To facilitate data exchange, wouldn’t it be better to use the (pseudo) html tags `<i>...</i>` etc. instead when writing CSL YAML or CSL JSON files?

Finally, a few ideas on useful information that could be added to the README:
- "yaml" could be added to the list of accepted biblio input file formats.
- It could be pointed out that CSL JSON, and CSL YAML are the native biblio formats for pandoc-citeproc, that all others need to be converted to the CSL data model (bibtex and biblatex by pandoc-citeproc itself, all others by bibutils), and that best results can be expected when using CSL JSON, CSL YAML, or biblatex.
- It could be mentioned that CSL JSON exported from Zotero can be used as biblio input if its "id" values are both wrapped in quotes and modified so they don't start with a digit.

Test input files:

article.ris:

```
TY  - JOUR
AU  - Olson, Hope A.
PY  - 2006
DA  - 2006//
TI  - Codes, Costs, and Critiques: The Organization of Information in Library Quarterly, 1931–2004
JO  - Library Quarterly
SP  - 19
EP  - 35
VL  - 76
IS  - 1
DO  - 10.1086/504343
ID  - item1
ER  - 
```

article.yaml:

```

---
references:
- title-short: Codes, costs, and critiques
  issue: 1
  page: 19-35
  title: "Codes, costs, and critiques: The organization of information in *Library
    Quarterly*, 1931–2004"
  volume: 76
  id: aj1
  issued:
    date-parts:
    - - 2006
  author:
  - given: Hope A.
    family: Olson
  container-title: Library Quarterly
  type: article-journal
  DOI: 10.1086/504343
...
```

article.json:

```
[
  {
    "DOI": "10.1086/504343",
    "author": [
      {
        "family": "Olson",
        "given": "Hope A."
      }
    ],
    "container-title": "Library Quarterly",
    "id": "item1",
    "issue": "1",
    "issued": {
      "date-parts": [
        [
          2006
        ]
      ]
    },
    "page": "19-35",
    "title": "Codes, costs, and critiques: The organization of information in *Library Quarterly*, 1931–2004",
    "title-short": "Codes, costs, and critiques",
    "type": "article-journal",
    "volume": "76"
  }
]
```
