### ISSUE TITLE
pandoc-citeproc and titlecase of word following mdash

### ISSUE THREAD

**Issue by reagle** [jgm/pandoc-citeproc#284]
from [email list](https://groups.google.com/d/msgid/pandoc-discuss/5801df38-08ca-073b-7bae-28fb21b7edc1%40reagle.org)

Given the YAML data below, it is rendered (using `chicago-author-date.csl`) as below with "---they" being lowercase when it should be title case. Am I right or am I doing something wrong?

> Groth, Aimee. 2015. “Entrepreneurs Don’t Have a Special Gene for
> Risk—they Come from Families with Money.” Web log message. Quartz.
> July 17.
> http://qz.com/455109/entrepreneurs-dont-have-a-special-gene-for-risk-they-come-from-families-with-money/.

```
---
references:
- id: Groth2015edh
  type: post-weblog
  genre: Web log message
  abstract: "Argument for risk and privilege by way of \\@LevineRubinstein2013wbe; \\@BlackEtal2015ort"
  author:
  - family: "Groth"
    given: "Aimee"
  container-title: "Quartz"
  custom2: "field-notes-2016-cat.mm"
  issued:
   year: 2015
   month: 07
   day: 17
  keyword: "privilege"
  title: "Entrepreneurs don't have a special gene for risk---they come from families with money"
  URL: "http://qz.com/455109/entrepreneurs-dont-have-a-special-gene-for-risk-they-come-from-families-with-money/"
  accessed:
   year: 2016
   month: 04
   day: 23
... 
@Groth2015edh
```
