### ISSUE TITLE
RIS parsing issue

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc-citeproc#286]
I have some odd issue with certain RIS input with pandoc-citeproc 0.10.4.

```
$ cat ~/Downloads/s41562-017-0082.ris 
TY  - JOUR
AU  - Starmans, Christina
AU  - Sheskin, Mark
AU  - Bloom, Paul
TI  - Why people prefer unequal societies
JA  - Nature Human Behaviour
PY  - 2017/04/07/online
VL  - 1
SP  - 0082
EP  -
PB  - Macmillan Publishers Limited
SN  -
UR  - http://dx.doi.org/10.1038/s41562-017-0082
L3  - 10.1038/s41562-017-0082
M3  - Perspective
L3  - 
ER  -
```

Notice these two lines:

```
SP  - 0082
EP  -
```

Now we convert it into YAML with `pandoc-citeproc -y -f ris <~/Downloads/s41562-017-0082.ris`. The result is this:

```yaml
---
references:
- id: Starmans2017
  type: article-journal
  author:
  - family: Starmans
    given: Christina
  - family: Sheskin
    given: Mark
  - family: Bloom
    given: Paul
  issued:
  - year: '2017'
    month: '4'
    day: '07'
  title: Why people prefer unequal societies
  container-title: Nature Human Behaviour
  publisher: Macmillan Publishers Limited SN -
  page: 0082 EP -
  volume: '1'
  note: Perspective
  URL: http://dx.doi.org/10.1038/s41562-017-0082
...
```

Notice the tails of `publisher` and `page` fields:

```yaml
  publisher: Macmillan Publishers Limited SN -
  page: 0082 EP -
```
