### ISSUE TITLE
numerical styles with second-field-align="flush"

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#29]
Using numerical styles such as nature.csl which contain the csl directive `second-field-align="flush"` in `<bibliography ...>`, the bibliography is expected to be rendered like a numbered list. 

(There are also a few styles with `second-field-align="margin"`, see list at https://gist.github.com/gjuggler/8222414, but since I don't think pandoc can handle stuff in margins these are probably best formatted just like the ones with `second-field-align="flush"`.)

In addition, there should be no space before the superscripted citation numbers. (Citation numbers always appearing _before_ final punctuation seems to be intentional, however, as a look at a number of recent "Nature" articles shows, and the fact that pandoc ignores page numbers is fine since these just aren't supposed to be used with such styles.)

The "et al" issue has been reported before, see https://github.com/jgm/pandoc-citeproc/issues/27.

There are a few other unexpected details, such as missing location and "ed.", but these are csl style errors.

```
pandoc -s --filter pandoc-citeproc -t markdown-citations <<EOT

Lorem [@arj1]. Ipsum [@boo1, 12-34; @inc1].

# References {-}

---
csl: nature.csl
references:
- page: 271-279
  title: By rail and stage to Galena
  id: inc1
  issued:
    date-parts:
    - - 1968
  author:
  - given: Elizabeth F. L.
    family: Ellet
  container-title: "Prairie state: Impressions of Illinois, 1673–1967, by travelers
    and other observers"
  editor:
  - given: Paul M.
    family: Angle
  publisher: University of Chicago Press
  type: chapter
  publisher-place: Chicago
- title-short: Freakonomics
  title: 'Freakonomics: A rogue economist explores the hidden side of everything'
  id: boo1
  issued:
    date-parts:
    - - 2005
  author:
  - given: Steven D.
    family: Levitt
  - given: Stephen J.
    family: Dubner
  publisher: William Morrow
  type: book
  publisher-place: New York
- title-short: Codes, costs, and critiques
  issue: 1
  page: 19-35
  title: "Codes, costs, and critiques: The organization of information in *Library
    Quarterly*, 1931–2004"
  volume: 76
  id: arj1
  issued:
    date-parts:
    - - 2006
  author:
  - given: Hope A.
    family: Olson
  container-title: Library Quarterly
  type: article-journal
  DOI: 10.1086/504343
...
EOT
```

Actual output:

```
Lorem ^1^. Ipsum ^2,3^.

<div class="references">

References {#references .unnumbered}
==========

1.Olson, H. A. *et al.* Codes, costs, and critiques: The organization of
information in *Library Quarterly*, 1931–2004. *Library Quarterly*
**76,** 19–35 (2006).

2.Levitt, S. D. & Dubner, S. J. *et al.* *Freakonomics: A rogue
economist explores the hidden side of everything*. (William Morrow,
2005).

3.Ellet, E. F. L. *et al.* in *Prairie state: Impressions of Illinois,
1673–1967, by travelers and other observers* (Angle, P. M.) 271–279
(University of Chicago Press, 1968).

</div>
```

Expected output:

```
Lorem^1^. Ipsum^2,3^.

<div class="references">

References {#references .unnumbered}
==========

1.  Olson, H. A. *et al.* Codes, costs, and critiques: The organization of
    information in *Library Quarterly*, 1931–2004. *Library Quarterly*
    **76,** 19–35 (2006).

2.  Levitt, S. D. & Dubner, S. J. *et al.* *Freakonomics: A rogue
    economist explores the hidden side of everything*. (William Morrow,
    2005).

3.  Ellet, E. F. L. *et al.* in *Prairie state: Impressions of Illinois,
    1673–1967, by travelers and other observers* (Angle, P. M.) 271–279
    (University of Chicago Press, 1968).

</div>
```
