### ISSUE TITLE
CSL in YAML header doesn't work when using a full path

### ISSUE THREAD

**Issue by svannoy** [jgm/pandoc-citeproc#291]
I am using APA csl to create bibliographies in my presentations for different courses I teach. I can specify a full to my citation library, but not to the csl file. 

For example, the following works just fine:
```
---
title: "My Class Presentation"
csl: apa.csl
output:
  html_document:
    css: ~/Documents/GitHub/custom-css/csp-notes-markdown.css
  html_notebook: default
  pdf_document: default
  word_document: default
bibliography: "~/Dropbox/UMB/Classes/COU 606 Ethics/counsl-606-slides/my-606-citations.bib"
---


[@houser2006culturally]

# Bibliography
```

But, the following does not work: 

 ```
---
title: "My Class Presentation"
csl: ~/Documents/GitHub/custom-css/apa.csl
output:
  html_document:
    css: ~/Documents/GitHub/custom-css/csp-notes-markdown.css
  html_notebook: default
  pdf_document: default
  word_document: default
bibliography: "~/Dropbox/UMB/Classes/COU 606 Ethics/counsl-606-slides/my-606-citations.bib"
---

[@houser2006culturally]

# Bibliography
```

The second case generates the following error. Note, I am sure that a copy of the file "apa.csl" does exist in the target directory:

```
pandoc-citeproc: Error parsing XML file apa.csl: apa.csl: openBinaryFile: does not exist (No such file or directory)
pandoc: Error running filter /usr/local/bin/pandoc-citeproc
Filter returned error status 1
```

My current solution is to create copies of apa.csl in all of my course/presentation folders, but it would be ideal to be able to link to one copy (whereas I don't mind so much having separate bibliography files).

Thanks
Steven
