### ISSUE TITLE
Citation sorting with additional citation text

### ISSUE THREAD

**Issue by garrettdashnelson** [jgm/pandoc-citeproc#292]
This is something of an extension of #101.

When a CSL has a `<sort>` field set for the ordering of parenthetical citations, such as alphabetically by author, additional commentary in a parenthetical citation is disrupted.

For instance, the following:

`A fascinating research tidbit [@Zanadu1999, p. 35; see for comparison @Aalto2005] ...`

when rendered with an alphabetical-order citer (e.g., [SAGE-Harvard](http://www.zotero.org/styles/sage-harvard)) will produce

`A fascinating research tidbit (see for comparison Aalto, 2005; Zanadu, 1999: 35)`

Ideally the filter would divide citations up into sub-blocks at each point that it finds text which is not a citation reference, and order each sub-block according to the CSL's configuration. Thus, if we had a complex citation like:

`Disagreements abound [@Xylax2016; see also @Yi2014; @Ang2017; for a contrary view, see @Mutt2012]`

We would divide the citation up into three sub-blocks, alphabetically order each, and produce:

`Disagreements abound (Xylax, 2016; see also Ang 2017; Yi 2014; for a contrary view, see Mutt, 2012)`

**Comment by jgm** [comment]
>   Ideally the filter would divide citations up into sub-blocks at each
>   point that it finds text which is not a citation reference, and order

In

>   A fascinating research tidbit [@Zanadu1999, p. 35; see for comparison
>   @Aalto2005] ...

there are two citation references; the first has a suffix
and the second has a prefix.  So I don't see any other
reasonable way for "sort" to work than the way it's working.

Does citeproc-js behave differently?

**Comment by jgm** [comment]
Test case
```
---
references:
- id: doe
  type: article
  author:
      family: Doe
  issued:
      year: 2007
- id: zoe
  type: article
  author:
      family: Zoe
  issued:
     - year: 2009
- id: roe
  type: article
  author:
      family: Roe
  issued:
     - year: 2007
csl: ../styles/sage-harvard.csl
...

[@zoe; @roe; see for comparison @doe, p. 3]
```
