### ISSUE TITLE
Dependent CSL styles fail

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#30]
Using dependent CSL styles (see http://citationstyles.org/downloads/specification.html#dependent-styles) such as http://github.com/citation-style-language/styles/blob/master/dependent/3-biotech.csl fails with "pandoc-citeproc: error while parsing the XML string" – while using the parent CSL style (here, http://github.com/citation-style-language/styles/blob/master/dependent/springer-basic-author-date.csl) works as expected.
See also https://groups.google.com/forum/?fromgroups&hl=en#!topic/pandoc-discuss/tltBY7mgjW0.

Example:

```
pandoc -s --filter pandoc-citeproc -t markdown-citations << EOT

Foo [@item1].

# References {-}

---
csl: 3-biotech.csl
references:
- id: item1
  issue: 1
  page: 19-35
  title: "Codes, costs, and critiques: The organization of information in *Library
    Quarterly*, 1931–2004"
  volume: 76
  issued:
    date-parts:
    - - 2006
  author:
  - given: Hope A.
    family: Olson
  container-title: Library Quarterly
  type: article-journal
...
EOT

pandoc -s --filter pandoc-citeproc -t markdown-citations << EOT

Foo [@item1].

# References {-}

---
csl: springer-basic-author-date.csl
references:
- id: item1
  issue: 1
  page: 19-35
  title: "Codes, costs, and critiques: The organization of information in *Library
    Quarterly*, 1931–2004"
  volume: 76
  issued:
    date-parts:
    - - 2006
  author:
  - given: Hope A.
    family: Olson
  container-title: Library Quarterly
  type: article-journal
...
EOT
```
