### ISSUE TITLE
Plural "issue" term used instead of singular

### ISSUE THREAD

**Issue by scarwire** [jgm/pandoc-citeproc#307]
This is a rather nitpicky issue, but with a number of French csl styles the symbol "nᵒ" (indicating the issue number of a journal) is incorrectly rendered as "nᵒˢ". I think this is coming from line 172 of [locales/locales-fr-FR.xml](https://github.com/jgm/pandoc-citeproc/blob/master/locales/locales-fr-FR.xml) and not from any of the csl styles themselves, which are rendered correctly for example by the Zotero LibreOffice plugin.

A couple of affected csl styles: 
[Le Tapuscrit (full note)](https://www.zotero.org/styles/le-tapuscrit-note)
[Vingtième siècle. Revue d'histoire](https://www.zotero.org/styles/vingtieme-siecle)

Minimal working example:
```
---
lang: fr-FR
csl: le-tapuscrit-note.csl
references:
- id: bazin_cybernetique_1954
  type: article-journal
  title: La Cybernétique d'André Cayatte
  container-title: Cahiers du cinéma
  page: 22-27
  issue: '36'
  author:
    - family: Bazin
      given: André
  issued:
    date-parts:
      - - 1954
        - 6
...

Bonjour[@bazin_cybernetique_1954] !
```

The footnote is rendered as:
> André Bazin, « La Cybernétique d’André Cayatte », _Cahiers du cinéma_, juin 1954, nᵒˢ 36, p. 22‑27.

It should be rendered as:
> André Bazin, « La Cybernétique d’André Cayatte », _Cahiers du cinéma_, juin 1954, nᵒ 36, p. 22‑27.

Thanks very much in any case!
