### ISSUE TITLE
First note number missing with oscola.csl

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#31]
Citations are rendered incompletely when using the oscola.csl style file: For the article-journal type (the only one I tested so far), year, journal title, volume and start page are missing in both note and bibliography, and notes referring to subsequent citations lack "(n. ...)". Output from Zotero/LibreOffice using the same style file is as expected.

See report at https://groups.google.com/forum/?fromgroups&hl=en#!topic/pandoc-discuss/DUe6ZfQpOpU

Example:

```
pandoc --filter pandoc-citeproc -t markdown-citations <<EOT

Foo [@item1]. Bar [@item2]. Baz [@item1].

---
csl: oscola.csl
references:
- title-short: Codes, costs, and critiques
  issue: 1
  page: 19-35
  title: "Codes, costs, and critiques: The organization of information in *Library
    Quarterly*, 1931–2004"
  volume: 76
  id: item1
  issued:
    date-parts:
    - - 2006
  author:
  - given: Hope A.
    family: Olson
  container-title: Library Quarterly
  type: article-magazine
  DOI: 10.1086/504343
- title: Second title
  id: item2
...
EOT
```

Actual output:

```
Foo.[^1] Bar.[^2] Baz.[^3]

Olson HA, ‘Codes, Costs, and Critiques: The Organization of Information
in *Library Quarterly*, 1931–2004’

‘Second Title’

[^1]: Hope A. Olson, ‘Codes, Costs, and Critiques: The Organization of
    Information in *Library Quarterly*, 1931–2004’.

[^2]: ‘Second Title’.

[^3]: Olson.
```

Expected output:

```
Foo.[^1] Bar.[^2] Baz.[^3]

Olson HA, ‘Codes, Costs, and Critiques: The Organization of Information
in *Library Quarterly*, 1931–2004’ (2006) 76 Library Quarterly 19

‘Second Title’

[^1]: Hope A Olson, ‘Codes, Costs, and Critiques: The Organization of 
    Information in *Library Quarterly*, 1931–2004’ (2006) 76 Library Quarterly 19.

[^2]: ‘Second Title’.

[^3]: Olson (n 2).
```
