### ISSUE TITLE
Separator between months/seasons missing when beginyear < endyear

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#312]
In pandoc-citeproc, this issue occurs with apa.csl (but not with chicago-autor-date.csl).

If beginyear and endyear do not differ, pandoc-citeproc formats this as expected, though (with apa.csl).

Most likely this is not caused by the style file, since the output from Zotero/citeproc-js/LO is as expected using apa.csl.

Example:

```
pandoc -F pandoc-citeproc --biblio=test.yaml -t plain --csl=apa.csl << EOT

@item1; @item2; @item3

---
references:
- id: item1
  type: webpage
  issued:
  - year: '-12'
    month: '1'
  - year: '12'
    month: '12'
  title: Title

- id: item2
  type: webpage
  issued:
  - year: '2016'
    month: '11'
  - year: '2017'
    month: '12'
  title: Title

- id: item3
  type: webpage
  issued:
  - year: '2016'
    season: '1'
  - year: '2017'
    season: '2'
  title: Title
...
EOT
```

Actual output:

```
(“Title,” 12BC–12ADa); (“Title,” 2016–2017b); (“Title,” 2016–2017c)

Title. (12BC–12ADa, JanuaryDecember).

Title. (2016–2017b, NovemberDecember).

Title. (2016–2017c, SpringSummer).
```

Expected:

```
(“Title,” 12BC–12ADa); (“Title,” 2016–2017b); (“Title,” 2016–2017c)

Title. (12BC–12ADa, January–December).

Title. (2016–2017b, November–December).

Title. (2016–2017c, Spring–Summer).
```

The disambiguation letters are wrong, too – expected: “2016–2017a” and “2016–2017b”.
