### ISSUE TITLE
pandoc-citeproc failing to parse yaml (regression?)

### ISSUE THREAD

**Issue by reagle** [jgm/pandoc-citeproc#316]
As discussed on [list](https://groups.google.com/forum/#!topic/pandoc-discuss/Ly-knRTt7gA) the following causes a parser error. I suspect the parser is having an issue with the season field, though it doesn't like if I use a number 1..4 either...

``` 
--- 
references: 
- id: MooreOMaidinMcelligott2002csc 
  type: article-journal 
  abstract: "145 new computer-systems students completed the \'Cognitive Style Index\' (Allinson & Hayes, 1996) and a demographic questionnaire. A significant correlation between performance and cognitive style was found with those students indicating a preference for analytic thinking more likely to have entered University with above average performance scores (taught or selected for that). Showed \'higher than average tendencies towards analytical cognitive styles\': 43.34 (CS) > 41.64 (other); (min=20; max=67; SD 11.43; MAX=76;); 56% were higher" 
  author: 
  - family: "Moore" 
    given: "Sarah" 
  - family: "O'Maidin" 
    given: "Donncha" 
  - family: "Mcelligott" 
    given: "Annette" 
  custom2: "lh.mm" 
  issued: 
    year: 2002 
    season: Spring 
  DOI: "10.1007/BF02940938" 
  container-title: "Journal of Computing in Higher Education" 
  issue: "2" 
  page: "45-67" 
  title-short: "Cognitive styles among computer systems students" 
  title: "Cognitive styles among computer systems students: preliminary findings" 
  URL: "http://link.springer.com/article/10.1007/BF02940938" 
  accessed: 
    year: 2015 
    month: 11 
    day: 19 
  volume: "14" 
... 
```
