### ISSUE TITLE
Sorting bibliographies with special characters

### ISSUE THREAD

**Issue by kchalipa** [jgm/pandoc-citeproc#320]
Hi all,

I've run into a challenge with pandoc-citeproc regarding the way it sorts special characters. It seems that *any* special character (even common glyphs like à) or diacritic is sorted after the letter Z, which can cause major sorting problems in large bibliographies. I posted an example of this on [StackExchange](https://stackoverflow.com/questions/48358317/alphabetically-sort-special-characters-in-pandoc-citeproc-bibliography); basically what you'll see is that a name like Ábe will be sorted after a name like Aze. This strikes me as an issue that would affect many writers who rely on special characters or diacritics in their work--is there any way to resolve this?

As a further note, I will point out that different authors may have different sorting criteria that are hard to cover in a one-size-fits-all approach. For example, I might want to order my bibliography "San, Šen, Son, Šun", while another author would want to treat the Š as its own letter (San, Son, Šen, Šun). In addition, there are disciplines that use extra characters like ʿ or ʾ that are typically ignored altogether in alphabetical sorting, but are currently sent to the end of the alphabet. Given how idiosyncratic these scenarios can get, the best solution that I can think of is to include some kind of sort key that lets me tell the parser where to put the entry; so if I have a citation like "al-ʿUdhrī" I could tell it to be sorted not under "a" nor under "z" but under "u", as though it were "Udhri". Such solutions have been devised for [BibTeX](http://www.tex.ac.uk/FAQ-bibprefixsort.html); is there, or could there be, something similar with pandoc-citeproc?

Sorry if this has already been answered elsewhere and I failed to find it.

**Comment by jgm** [comment]
I'm not sure what to do about this.  There are different ways to sort, as you note, and it's hard to see how to incorporate an option for this.

You could try compiling pandoc-citeproc with the `unicode_collation` flag to see if that gives you different results.  (requires the icu library)

**Comment by kchalipa** [comment]
Thanks! I'll look into it and report back about what I find.

I see what you mean about there being no easy option; looking through the many fields available in the [CSL editor](http://editor.citationstyles.org/visualEditor/), I didn't see anything to match the `sortname` or `sortkey` fields provided by biblatex (although I'm no expert on CSL, or any of this really, so there could well be something I don't know about). One partial workaround—if converting to html, rtf, docx, or the like—is simply to sort the bibliography with another program in the final stage of preparation, although that does require turning off the em-dashes below repeated authors (not sure how to do that) and could introduce new problems with non-dropping particles; but it's a start.

**Comment by njbart** [comment]
Using ICU is almost certainly the way to go here. This used to work well a few years back, though I stopped including it when compiling pandoc-citeproc when I switched from cabal to stack.

ICU can do language (or rather, locale) sensitive collation. (For example, if set to `es-ES` (Spanish) it collates `ñ` as a separate letter after `n`.)

As to “extra characters”, these don’t seem to be displayed properly in the post above, so I can’t say anything on these.

Collating “al-ʿUdhrī” under “U” merely requires setting `demote-non-dropping-particle` to `sort-only` in the CSL style file.

And yes, there is nothing like the biblatex  `sortname` or `sortkey` fields in CSL. (In a pinch, you could borrow an otherwise unused CSL variable, and use it as a sortname field, but you’d probably have to populate it for *all* entries, not just, as in biblatex, the problematic ones.)

@jgm – How exactly would I compile pandoc-citeproc with the `unicode_collation` flag, using `stack`?

**Comment by kchalipa** [comment]
Thanks for the further comments! Just to clarify my extra characters, I posted two (small) glyphs that are used in Arabic transliteration, *ayn* (ʿ) and *hamza* (ʾ) --- U02BF and U02BE respectively. Since they fall outside the normal set of Latin characters, they are typically ignored in sorting/parsing; some programs do this, but the vast majority (including citeproc, from what I've seen) sort them at the end of the alphabet. Because of the *ayn*, the example we're discussing, al-ʿUdhrī, would get sorted after Z, which may just be how the cookie crumbles, unless we used the unused-variable trick or compiling with ICU works out. I'll note that when I used biblatex for my bibliographies, it did handle these characters very well (by ignoring them), so maybe we can be optimistic!

**Comment by jgm** [comment]
+++ Nick Bart [Feb 03 18 08:27 ]:
>   [1]@jgm – How exactly would I compile pandoc-citeproc with the
>   unicode_collation flag, using stack?

stack install pandoc-citeproc --flag "pandoc-citeproc:unicode_collation"

**Comment by njbart** [comment]
I’m a little confused now – I thought we had this issue sorted out in #122. 

I am currently installing the dev version using the following script (based on the [instructions from the pandoc wiki](https://github.com/jgm/pandoc/wiki/Installing-the-development-version-of-pandoc); I’ve been using this script for a while, it’s only pandoc-citeproc that gets a special treatment now – comments, e.g., on whether this is the optimal sequence, are welcome):

```
buildhome=/Users/nick/src/pandoc-build

for package in cmark-hs pandoc-types texmath zip-archive pandoc
do
printf "\n$package ...\n"
cd $buildhome/$package
git pull
stack install
done


for package in pandoc-citeproc
do
printf "\n$package ...\n"
cd $buildhome/$package
git pull
stack install --flag "pandoc:unicode_collation"
done
```

Now, the following script, which tries both the latest dev version (first in my path) and the homebrew version (at /usr/local/bin) …

```
cat > test.yaml << EOT
---
nocite: '@*'
references:
- id: item1
  type: book
  author:
  - family: Author  
- id: item2
  type: book
  author:
  - family: Zuthor
- id: item3
  type: book
  author:
  - family: Øøthor
...
EOT

printf "\nlatest dev -- en-US:\n\n"
printf "\n---\nnocite: '@*'\n..." | pandoc -s -F pandoc-citeproc -t plain --biblio test.yaml -M lang='en-US'
printf "\nlatest dev -- da-DK:\n\n"
printf "\n---\nnocite: '@*'\n..." | pandoc -s -F pandoc-citeproc -t plain --biblio test.yaml -M lang='da-DK'

printf "\nlatest homebrew -- en-US:\n\n"
printf "\n---\nnocite: '@*'\n..." | /usr/local/bin/pandoc -s -F /usr/local/bin/pandoc-citeproc -t plain --biblio test.yaml -M lang='en-US'
printf "\nlatest homebrew -- da-DK:\n\n"
printf "\n---\nnocite: '@*'\n..." | /usr/local/bin/pandoc -s -F /usr/local/bin/pandoc-citeproc -t plain --biblio test.yaml -M lang='da-DK'
```

outputs this (some newlines removed):

```
latest dev -- en-US:
Author. n.d.
Zuthor. n.d.
Øøthor. n.d.

latest dev -- da-DK:
Author. u.å.
Zuthor. u.å.
Øøthor. u.å.

latest homebrew -- en-US:

Author. n.d.
Zuthor. n.d.
Øøthor. n.d.

latest homebrew -- da-DK:
Author. u.å.
Zuthor. u.å.
Øøthor. u.å.
```

… so no difference at all. For da-DK, this collation seems correct (Ø after Z), but for en-US, it is not (CMoS 16e, 16.67, “Alphabetizing accented letters” quite clearly calls for disregarding any accents, so we should have A – Ø – Z here).

`lang` seems to be parsed correctly, as judged by the different abbreviations for “no date”.

Just in case, I’m using macOS 10.13.3, and this is the output I get from `locale` (possibly relevant, again, see #122):

```
LANG="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL=
```

Any ideas?

**Comment by njbart** [comment]
Ok, this seems to have worked. (Should we add the complete command I had to use, `stack install pandoc pandoc-citeproc --flag "pandoc-citeproc:unicode_collation" --extra-lib-dirs=/usr/local/opt/icu4c/lib --extra-include-dirs=/usr/local/opt/icu4c/include`, to the wiki?)

Now I see two new issues, one fundamental, and one, well, bizarre:

The fundamental one is, it seems correct collation of accented characters in English is *only* available if ICU is used, so the question is, could it be included by default?

The bizarre one is, using `da-DK`, “Aaa” (but not “Abb”!) all of a sudden gets sorted after “Zzz”:

```
cat > test.yaml << EOT
---
references:
- id: x1
  type: article-journal
  author:
  - family: Aaa
- id: x4
  type: article-journal
  author:
  - family: Abb
- id: x2
  type: article-journal
  author:
  - family: Zzz
- id: x3
  type: article-journal
  author:
  - family: Ååå
...
EOT

printf "\nlatest dev -- en-US:\n\n"
printf "\n---\nnocite: '@*'\n..." | pandoc -s -F pandoc-citeproc -t plain --biblio test.yaml -M lang='en-US'
printf "\nlatest dev -- da-DK:\n\n"
printf "\n---\nnocite: '@*'\n..." | pandoc -s -F pandoc-citeproc -t plain --biblio test.yaml -M lang='da-DK'
```

Output:

```
latest dev -- en-US:
Aaa. n.d.
Ååå. n.d.
Abb. n.d.
Zzz. n.d.

latest dev -- da-DK:
Abb. u.å.
Zzz. u.å.
Aaa. u.å.
Ååå. u.å.
```

**Comment by njbart** [comment]
As to special characters such as ayn and hamza, it seems these are currently sorted after “Z” in en-US and a few other locales I tried, even when using ICU. (Other special characters, e.g., a straight apostrophe at the start of a name, do not influence sorting, so ignoring specific characters certainly does seem to be possible.)

ICU does seem to provide a mechanism for [customizing collation](http://userguide.icu-project.org/collation/customization), so there might be a possibility to make this user-configurable, e.g., via a pandoc-citeproc flag.

**Comment by njbart** [comment]
More data points:

Apostrophes inside a name (e.g., O’Neill) are not ignored when collating with ICU and en-US:

```
pandoc -s -F pandoc-citeproc -t plain << EOT

Foo [@item1; @item2; @item3].

---
lang: en-US
references:
- id: item1
  type: book
  author:
  - family: Onassis  
    given: Aristotle
  issued:
  - year: 2013
  title: Title
- id: item2
  type: book
  author:
  - family: O'Neill
    given: Eugene
  issued:
  - year: 2013
  title: Title
- id: item3
  type: book
  author:
  - family: Ongaro
    given: Francesco
    dropping-particle: dall'
  issued:
  - year: 2013
  title: Title
...
EOT
```

Output (some newlines removed):

```
Foo (Onassis 2013; O’Neill 2013; Ongaro 2013).

O’Neill, Eugene. 2013. _Title_.
Onassis, Aristotle. 2013. _Title_.
Ongaro, Francesco dall’. 2013. _Title_.
```

Expected, according to the example in CMS 16e, 16.74:

```
Onassis, Aristotle. 2013. _Title_.
O’Neill, Eugene. 2013. _Title_.
Ongaro, Francesco dall’. 2013. _Title_.
```

Zotero/citeproc-js/LO get this one right, BTW.

**Comment by jgm** [comment]
Perhaps the best place for a note about the proper stack invocation for installing with ICU support would be the README for this repository.  Note that the library locations may vary depending on the system.

We use the `rfc5051` package for sorting if ICU isn't enabled. This gets some default sorting right for English and western European languages, but not all.

The apostrophe issue should not be too hard to deal with, I think.

As for ICU collation customization, one would first have to investigate how this is exposed in the haskell icu package.

**Comment by jgm** [comment]
OK, with b2bd8ec71ec83d261352f161bffebe077bfbf922 I get
```
Foo (Onassis 2013; O’Neill 2013; Ongaro 2013).

Onassis, Aristotle. 2013. _Title_.

Ongaro, Francesco dall’. 2013. _Title_.

O’Neill, Eugene. 2013. _Title_.
```
Should we also be lowercasing everything before comparing?

**Comment by njbart** [comment]
But your non-ICU output still does not conform with CMS: the order should be Onassis – O’Neill – Ongaro. (BTW, APA has the same rule: “Disregard the apostrophe”, APA Manual 6e, 6.25.)

> Should we also be lowercasing everything before comparing?

I would guess so – after all, CMS (16e, 16.71) lists the following, which clearly implies case-independent sorting:

> Beauvoir, Simone de 
Ben-Gurion, David 
Costa, Uriel da
da Cunha, Euclides 
D'Amato, Alfonse
de Gaulle, Charles
di Leonardo, Micaela

Since you seem to have decided to have pandoc-citeproc deal with the apostrophe issue itself rather than relying on a library, would it be too difficult to simply strip out ayn and hamza, too, before sorting? (CMS 16e, 11.96 ff. mentions ayn and hamza, but does not say anything explicit on whether they should be disregarded when sorting. The OP seems to think so, and I tend to agree.)

Making this user-configurable would be even better, but so far I haven’t found any hint either how to access the customization mechanism in the haskell icu package.

**Comment by jgm** [comment]
+++ Nick Bart [Feb 06 18 22:22 ]:
>   But your non-ICU output still does not conform with CMS: the order
>   should be Onassis – O’Neill – Ongaro. (BTW, APA has the same rule:
>   “Disregard the apostrophe”, APA Manual 6e, 6.25.)

Yes, I know. This is due to the case sensitivity issue.

**Comment by njbart** [comment]
> Yes, I know. This is due to the case sensitivity issue.

I see. So that’s another indication that CMS requires case-insensitive sorting. 

APA requires this as well; in addition, it seems that for APA spaces and hyphens should be disregarded, too. (As they put it: “Alphabetize letter by letter. When alphabetizing surnames, remember that “nothing precedes something”: Brown, J. R., precedes Browning, A. R., even though i precedes j in the alphabet.” APA Manual, 6e, 6.25.) I couldn’t find anything in CMS so far that would contradict this, so it’d be probably worth implementing this rule, too.

Test case:

```
pandoc -s -F pandoc-citeproc -t plain << EOT

Expected (according to APA Manual, 6e, 6.25):  
Benjamin, A. S.  
ben Yaakov, D.  
Brown, J. R.  
Browning, A. R.  
Girard, J.-B.  
Girard-Perregaux, A. S.   
Ibn Abdulaziz, T.  
Ibn Nidal, A. K. M.   
López, M. E.  
López de Molina, G.   
Singh, Y.  
Singh Siddhu, N.  
Villafuerte, S. A.  
Villa-Lobos, J. 

Foo [@item1; @item2; @item3; @item4; @item5; @item6; @item7; @item8; @item9; @item10; @item11; @item12; @item13; @item14].

---
csl: apa.csl
references:
- id: item1
  author:
  - family: Benjamin, A. S.
- id: item2
  author:
  - family: ben Yaakov, D.
- id: item3
  author:
  - family: Brown, J. R.
- id: item4
  author:
  - family: Browning, A. R.
- id: item5
  author:
  - family: Girard, J.-B.
- id: item6
  author:
  - family: Girard-Perregaux, A. S. 
- id: item7
  author:
  - family: Ibn Abdulaziz, T.
- id: item8
  author:
  - family: Ibn Nidal, A. K. M. 
- id: item9
  author:
  - family: López, M. E.
- id: item10
  author:
  - family: López de Molina, G. 
- id: item11
  author:
  - family: Singh, Y.
- id: item12
  author:
  - family: Singh Siddhu, N.
- id: item13
  author:
  - family: Villafuerte, S. A.
- id: item14
  author:
  - family: Villa-Lobos, J. 
...
EOT
```

Actual output, with ICU, only the reference list shown:

```
ben Yaakov, D. (n.d.).
Benjamin, A. S. (n.d.).
Brown, J. R. (n.d.).
Browning, A. R. (n.d.).
Girard-Perregaux, A. S. (n.d.).
Girard, J.-B. (n.d.).
Ibn Abdulaziz, T. (n.d.).
Ibn Nidal, A. K. M. (n.d.).
López de Molina, G. (n.d.).
López, M. E. (n.d.).
Singh Siddhu, N. (n.d.).
Singh, Y. (n.d.).
Villa-Lobos, J. (n.d.).
Villafuerte, S. A. (n.d.).
```

This shows that the sorting of all pairs, except “Brown/Browning” and “Ibn …/Ibn …” are wrong according to APA. Same actual sort order in the output with `chicago-author-date.csl`, BTW.

**Comment by njbart** [comment]
Ok, once again, this time names properly split into family/given/particles:

```
pandoc -s -F pandoc-citeproc -t plain << EOT

Expected (according to APA Manual, 6e, 6.25):  
Benjamin, A. S.  
ben Yaakov, D.  
Brown, J. R.  
Browning, A. R.  
Girard, J.-B.  
Girard-Perregaux, A. S.  
Ibn Abdulaziz, T.  
Ibn Nidal, A. K. M.  
López, M. E.  
López de Molina, G.  
Singh, Y.  
Singh Siddhu, N.  
Villafuerte, S. A.  
Villa-Lobos, J.

Foo [@item1; @item2; @item3; @item4; @item5; @item6; @item7; @item8; @item9; @item10; @item11; @item12; @item13; @item14].

---
csl: apa.csl
references:
- id: item1
  author:
  - family: Benjamin
    given: A. S.
- id: item2
  author:
  - family: Yaakov
    non-dropping-particle: ben
    given: D.
- id: item3
  author:
  - family: Brown
    given: J. R.
- id: item4
  author:
  - family: Browning
    given: A. R.
- id: item5
  author:
  - family: Girard
    given: J.-B.
- id: item6
  author:
  - family: Girard-Perregaux
    given: A. S.
- id: item7
  author:
  - family: Ibn Abdulaziz
    given: T.
- id: item8
  author:
  - family: Ibn Nidal
    given: A. K. M.
- id: item9
  author:
  - family: López
    given: M. E.
- id: item10
  author:
  - family: López de Molina
    given: G.
- id: item11
  author:
  - family: Singh
    given: Y.
- id: item12
  author:
  - family: Singh Siddhu
    given: N.
- id: item13
  author:
  - family: Villafuerte
    given: S. A.
- id: item14
  author:
  - family: Villa-Lobos
    given: J.
...
EOT
```

Output, with ICU:

```
ben Yaakov, D. (n.d.).
Benjamin, A. S. (n.d.).
Brown, J. R. (n.d.).
Browning, A. R. (n.d.).
Girard, J.-B. (n.d.).
Girard-Perregaux, A. S. (n.d.).
Ibn Abdulaziz, T. (n.d.).
Ibn Nidal, A. K. M. (n.d.).
López de Molina, G. (n.d.).
López, M. E. (n.d.).
Singh Siddhu, N. (n.d.).
Singh, Y. (n.d.).
Villa-Lobos, J. (n.d.).
Villafuerte, S. A. (n.d.).
```

Interestingly, using the proper family/given structure reverses the sort order of “Girard …”, so this looks ok now, too.

**Comment by njbart** [comment]
Two more test cases, from CMS 16e, 16.73 and .75 (with ICU, the “Mac”s look ok, the “Saint”s don’t):

```
pandoc -s -F pandoc-citeproc -t plain << EOT

From CMS 16e 16.73. Expected:

Macalister, Donald  
MacAlister, Paul  
Macauley, Catharine  
Macmillan, Harold  
Madison, James  
McAllister, Ward  
McAuley, Catherine  
McMillan, Edwin M.

Foo [@item1; @item2; @item3; @item4; @item5; @item6; @item7; @item8].

---
references:
- id: item1
  author:
  - family: Macalister
    given: Donald
- id: item2
  author:
  - family: MacAlister
    given: Paul
- id: item3
  author:
  - family: Macauley
    given: Catharine
- id: item4
  author:
  - family: Macmillan
    given: Harold
- id: item5
  author:
  - family: Madison
    given: James
- id: item6
  author:
  - family: McAllister
    given: Ward
- id: item7
  author:
  - family: McAuley
    given: Catherine
- id: item8
  author:
  - family: McMillan
    given: Edwin M.
...
EOT
```

Current output, with ICU:

```
Macalister, Donald. n.d.
MacAlister, Paul. n.d.
Macauley, Catharine. n.d.
Macmillan, Harold. n.d.
Madison, James. n.d.
McAllister, Ward. n.d.
McAuley, Catherine. n.d.
McMillan, Edwin M. n.d.
```

```
pandoc -s -F pandoc-citeproc -t plain << EOT

From CMS 16e 16.75. Expected:

Sainte-Beuve, Charles-Augustin  
Saint-Gaudens, Augustus  
Saint-Saëns, Camille  
San Martin, José de  
St. Denis, Ruth  
St. Laurent, Louis Stephen

Foo [@item1; @item2; @item3; @item4; @item5; @item6].

---
references:
- id: item1
  author:
  - family: Sainte-Beuve
    given: Charles-Augustin
- id: item2
  author:
  - family: Saint-Gaudens
    given: Augustus
- id: item3
  author:
  - family: Saint-Saëns
    given: Camille
- id: item4
  author:
  - family: San Martin
    given: José
    dropping-particle: de
- id: item5
  author:
  - family: St. Denis
    given: Ruth
- id: item6
  author:
  - family: St. Laurent
    given: Louis Stephen
...
EOT
```

Current output, with ICU:

```
Saint-Gaudens, Augustus. n.d.
Saint-Saëns, Camille. n.d.
Sainte-Beuve, Charles-Augustin. n.d.
San Martin, José de. n.d.
St. Denis, Ruth. n.d.
St. Laurent, Louis Stephen. n.d.
```
