### ISSUE TITLE
Italics cause problems with non-English title case when using CSL styles

### ISSUE THREAD

**Issue by scarwire** [jgm/pandoc-citeproc#322]
I'm writing my thesis in French and using pandoc-citeproc for the references. Sometimes I have article titles that includes parts in italics, which I've input in my YAML bibliography as ```_italics_``` using markdown. The problem is that when I do this, the title seems to revert to English title case.

What's strange is that this only happens when using French CSL styles, but don't see anything in the CSL styles themselves that would cause this behavior.

For example:

```
pandoc -s -F pandoc-citeproc -t plain << EOT

Foo[@timmory__justice_1950].

---
references:
- id: timmory__justice_1950
  type: article-journal
  title: '_Justice est faite_ : soyons justes'
  container-title: L'Écran français
  page: '12'
  issue: '272'
  language: fr-FR
  author:
    - family: Timmory
      given: François
  issued:
    - year: 1950
      month: 9
      day: 25
...
EOT
```

This gives the expected result, keeping French title case:
```
Timmory, François. 1950. “_Justice est faite_ : soyons justes.” _L’Écran
français_, no. 272 (September):12.
```

However, with all the French CSL styles I've tried, the part in italics reverts to English title case.

```
pandoc -s -F pandoc-citeproc --csl=annales.csl -t plain << EOT

Foo[@timmory__justice_1950].

---
references:
- id: timmory__justice_1950
  type: article-journal
  title: '_Justice est faite_ : soyons justes'
  container-title: L'Écran français
  page: '12'
  issue: '272'
  language: fr-FR
  author:
    - family: Timmory
      given: François
  issued:
    - year: 1950
      month: 9
      day: 25
...
EOT
```

This results in:
```
François TIMMORY, « _Justice Est Faite_ : soyons justes », _L’Écran
français_, 1950, nᵒ 272, p. 12.

[1] François TIMMORY, « _Justice Est Faite_ : soyons justes », _L’Écran
français_, 1950, nᵒ 272, p. 12.
```

Am I missing something that's causing the problem in the CSL styles? Or is this an issue with pandoc-citeproc?

Many thanks for all the work you do.
