### ISSUE TITLE
Incorrect handling of group with only empty variables

### ISSUE THREAD

**Issue by heikojansen** [jgm/pandoc-citeproc#338]
http://docs.citationstyles.org/en/stable/specification.html#group mandates that group elements which reference only empty variables should be omitted.

https://github.com/citation-style-language/styles/blob/3cd11790684db313a044897f726bb465cb1d7bc8/din-1505-2.csl#L212 contains the following macro:

```xml
<macro name="scale">
  <group>
    <text term="scale"/>
    <text prefix=" " variable="scale"/>
  </group>
</macro>
```

Processing records without scale information however leads to citations with the German word "Maßstab" in it, so obviously the ```text/@term``` is inserted even though there is no scale info.

    pandoc --filter pandoc-citeproc --bibliography bib.json --csl ./styles/din-1505-2.csl -t plain config.yml

    WOLFINGER, CHRISTINE: _Keine Angst vor Linux, Unix: ein Lehrbuch für
    Linux- und Unix-Anwender_. 11., vollst. überarb. Aufl. Berlin [u.a.] :
    Springer Vieweg, 2013 – Maßstab — ISBN 978-3-642-32078-1

Modifying the macro like this fixes the problem:

```xml
<macro name="scale">
  <choose>
    <if variable="scale">
      <group>
        <text term="scale"/>
        <text prefix=" " variable="scale"/>
      </group>
    </if>
  </choose>
</macro>
```

But according to the CSL spec this should not be necessary and the issue should instead be fixed in pandoc-citeproc (cf. citation-style-language/styles#3558)

config.yml
```yaml
---
pagetitle: Citation
lang: de
nocite: '@*'
...
```

bib.json
```json
[{"extent":"XVIII, 529 S. : Ill., graph. Darst.","publisher-place":"Berlin [u.a.]","title":"Keine Angst vor Linux, Unix: ein Lehrbuch für Linux- und Unix-Anwender","responsibility":"Christine Wolfinger","notes":["Gb. : ca. EUR 34.95 (DE), ca. EUR 35.93 (AT), ca. sfr 43.50 (freier Pr.)","10. Aufl. u.d.T. Wolfinger, Christine: Keine Angst vor Unix, Linux"],"subtitle":"ein Lehrbuch für Linux- und Unix-Anwender","keyword":"UNIX; LINUX","year":2013,"publisher":"Springer Vieweg","number-of-pages":"XVIII, 529 S. : Ill., graph. Darst.","id":"item-1","relatedWorks":[{"desc":"Xpert.press","search":"Xpert.press"}],"address":"Berlin [u.a.]","authors":["Wolfinger, Christine"],"edition":"11., vollst. überarb. Aufl.","completeTitle":"Keine Angst vor Linux, Unix: ein Lehrbuch für Linux- und Unix-Anwender","isbns":["978-3-642-32078-1","3-642-32078-3"],"author":[{"given":"Christine","family":"Wolfinger"}],"keywords":["UNIX","LINUX"],"issued":{"year":2013},"ISBN":"978-3-642-32078-1","type":"book"}]
```

```
~> rpm -q ghc-pandoc-citeproc
ghc-pandoc-citeproc-0.14.3.1-1.2.x86_64
```

```
~> rpm -q ghc-pandoc
ghc-pandoc-2.1.2-19.1.x86_64
```

OS is openSUSE Leap 42.3

**Comment by rmzelle** [comment]
Just want to confirm that the OP is right. It's an extremely common pattern in CSL styles. See http://docs.citationstyles.org/en/1.0.1/specification.html#group for the rule:

> cs:group implicitly acts as a conditional: cs:group and its child elements are suppressed if a) at least one rendering element in cs:group calls a variable (either directly or via a macro), and b) all variables that are called are empty.

**Comment by jgm** [comment]
Here's a consolidated test file: 338.md.
```
---
pagetitle: Citation
csl: din-1505-2.csl
lang: de
nocite: '@*'
references:
- id: item-1
  type: book
  author:
  - family: Wolfinger
    given: Christine
  issued:
  - year: 2013
  title: 'Keine Angst vor Linux, Unix: ein Lehrbuch für Linux- und Unix-Anwender'
  publisher: Springer Vieweg
  publisher-place: Berlin \[u.a.\]
  number-of-pages: 'XVIII, 529 S. : Ill., graph. Darst.'
  edition: 11., vollst. überarb. Aufl.
  keyword: UNIX; LINUX
  ISBN: 978-3-642-32078-1
...
```
Test with
```
pandoc -F pandoc-citeproc 338.md -t plain
```
