### ISSUE TITLE
“status: in press” fails to generate in-text citation (in some contexts)

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#371]
For items having `status: in press` (but no date), sometimes no in-text citation is generated (error message: `pandoc-citeproc: reference with no printed form`).

Example:

```
pandoc -s -F pandoc-citeproc -t plain << EOT

Foo [@item2; @item1].

# References {-}

---
references:
- id: item1
  type: book
  author:
  - family: Doe
    given: Jane
  status: in press
  title: Title one
- id: item2
  type: book
  author:
  - family: Doe
    given: Jane
  issued:
    - year: 2018
  title: Title two
...
EOT
```

Expected output:

```
Foo (Doe 2018, in press).

REFERENCES

Doe, Jane. 2018. _Title two_.

———. In press. _Title one_.
```

Actual output:

```
pandoc-citeproc: reference with no printed form
Foo (Doe 2018, ???).

REFERENCES

Doe, Jane. 2018. _Title two_.

———. In press. _Title one_.
```

Oddly enough, this depends on context: Reversing the order of the citations in the source file (i.e., `Foo [@item1; @item2]`) results in the expected output, as does quoting the problematic item by itself (`Foo [@item1]`).

On the other hand, quoting `@item1` twice (i.e., `Foo [@item1; @item1]`) results in the same kind of error:

```
pandoc-citeproc: reference with no printed form
Foo (Doe, in press, ???).

REFERENCES

Doe, Jane. In press. _Title One_.
```
