### ISSUE TITLE
Incorrect name disambiguation: “A. Doe, Doe, and Roe”

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#38]
In cases where a last name appears more than once among an entry’s authors, spurious initials appear, e.g., “A. Doe, Doe, and Roe” instead of “Doe, Doe, and Roe”.

The same effect is observed if the sequence is “Doe, Roe, Doe”; but not if it’s “Roe, Doe, Doe”.

Example:

```
pandoc --filter pandoc-citeproc -t markdown-citations <<EOT

@a

---
references:
- title: Title
  id: a
  issued:
    date-parts:
    - - 2007
  author:
  - given: Ann
    family: Doe
  - given: Ben
    family: Doe
  - given: Ron
    family: Roe
  type: article-journal
...

EOT
```

Actual output:

```
A. Doe, Doe, and Roe (2007)

<div class="references">

Doe, Ann, Ben Doe, and Ron Roe. 2007. “Title.”

</div>
```

Expected output:

```
Doe, Doe, and Roe (2007)

<div class="references">

Doe, Ann, Ben Doe, and Ron Roe. 2007. “Title.”

</div>
```
