### ISSUE TITLE
Incorrect format of editors’ names with apostrophes: “O’ConnorIan”

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#39]
```
pandoc --filter pandoc-citeproc -t markdown-citations <<EOT

@a

---
references:
- title: Chapter Title
  id: a
  issued:
    date-parts:
    - - 2014
  author:
  - given: John
    family: Doe
  container-title: Title
  editor:
  - given: Ian
    family: "O’Connor"
  publisher: Publisher
  publisher-place: Location
  page: 107-115
  type: chapter
...
EOT
```

Actual output:

```
Doe (2014)

<div class="references">

Doe, John. 2014. “Chapter Title.” In *Title*, edited by O’ConnorIan,
107–15. Location: Publisher.

</div>
```

Expected output:

```
Doe (2014)

<div class="references">

Doe, John. 2014. “Chapter Title.” In *Title*, edited by Ian O’Connor,
107–15. Location: Publisher.

</div>
```
