### ISSUE TITLE
When citing two sources with original publication dates, second one is formatted wrongly

### ISSUE THREAD

**Issue by odkr** [jgm/pandoc-citeproc#401]
Using the `chicago-author-date.csl` as a style sheet, when I cite two sources that have an `original-date` set, then `pandoc-citeproc` malformats the date of the second source. More precisely, it concatenates the original publication date and that of the cited edition, without spaces or square brackets.

For example:
```
$ cat << EOF | pandoc test.md -F pandoc-citeproc -t plain
> ---
> bibliography: test.json
> ---
> Haslanger [-@haslanger2012SocialConstructionDebunking; @haslanger2012FeminismMetaphysicsNegotiating] says p.
> EOF
Haslanger ([2003] 2012, 20002012) says p.
[...]
```
I'm using `pandoc` version 2.7.2 and `pandoc-citeproc` version 0.16.1.3.

I attached the CSL JSON [bibliography file](https://github.com/jgm/pandoc-citeproc/files/3113004/test.json.txt) the YAML header above references.

Thanks for looking into it!

**Comment by odkr** [comment]
If somebody else stumbles upon this thread, this Lua filter automatically fixes the error:

```Lua
function Cite (cite)
    local stringify = pandoc.utils.stringify
    local Str = pandoc.Str
    local Space = pandoc.Space
    local Span = pandoc.Span
    local inlines = cite.c[2]
    for i, inline in ipairs(inlines) do
         local ref, tail = stringify(inline):match('^(%d+)(.*)')
         if (ref and ref:len() == 8) then
             inlines[i] = Span({Str('[' .. ref:sub(1, 4) .. ']'), Space(),
                 Str(ref:sub(5, 8)), Str(tail)})
         end
    end
    return cite
end
```

Note, this filter doesn't *solve* anything. It just replaces text that looks like a malformated citation. And the formatting probably only makes sense for `chicago-author-date.csl`. Just run it after `pandoc-citeproc`.

**Comment by jgm** [comment]
Here's a standalone markdown file containing the references too:
```
---
references:
- id: haslanger2012SocialConstructionDebunking
  type: chapter
  author:
  - family: Haslanger
    given: Sally
  issued:
  - year: 2012
  original-date:
  - year: 2003
  title: 'Social Construction: The ‘Debunking’ Project'
  title-short: Social Construction
  container-title: 'Resisting Reality: Social Construction and Social Critique'
  publisher: Oxford University Press
  publisher-place: Oxford
  event-place: Oxford
  page: 113–138
  ISBN: 978-0-19-989262-4

- id: haslanger2012FeminismMetaphysicsNegotiating
  type: chapter
  author:
  - family: Haslanger
    given: Sally
  issued:
  - year: 2012
  original-date:
  - year: 2000
  title: 'Feminism in Metaphysics: Negotiating the Natural'
  container-title: 'Resisting Reality: Social Construction and Social Critique'
  publisher: Oxford University Press
  publisher-place: Oxford
  event-place: Oxford
  page: 139–157
  ISBN: 978-0-19-989262-4
  language: en
...

Haslanger [-@haslanger2012SocialConstructionDebunking; @haslanger2012FeminismMetaphysicsNegotiating] says p.
```
