### ISSUE TITLE
Symbols in title not escaped in HTML nor LaTeX output.

### ISSUE THREAD

**Issue by mpark** [jgm/pandoc-citeproc#404]
```
pandoc 2.7.2
pandoc-citeproc 0.16.1.3
```

Given:
```
[@P0655R0]

---
references:
  - id: P0655R0
    citation-label: P0655R0
    title: "visit<R>: Explicit Return Type for visit"
    author:
      - family: Michael Park, Agustín Bergé
    issued:
      year: 2017
    URL: https://wg21.link/p0655r0
---
```

The HTML output produces:
```html
<p><span class="citation" data-cites="P0655R0">(Michael Park, Agustín Bergé 2017)</span></p>
<div id="refs" class="references" role="doc-bibliography">
<div id="ref-P0655R0">
<p>Michael Park, Agustín Bergé. 2017. “Visit<R>: Explicit Return Type for Visit.” <a href="https://wg21.link/p0655r0">https://wg21.link/p0655r0</a>.</p>
</div>
</div>
```
where `<` and `>` are not escaped. This results in the `<R>` being interpreted as an HTML tag.

For LaTeX, it generates:

```latex
(Michael Park, Agustín Bergé 2017)

\hypertarget{refs}{}
\leavevmode\hypertarget{ref-P0655R0}{}%
Michael Park, Agustín Bergé. 2017. ``Visit: Explicit Return Type for
Visit.'' \url{https://wg21.link/p0655r0}.
```
where the `<R>` seems to be disappeared.
