### ISSUE TITLE
Incorrect sorting with mixed Y, YMD, and YMD-YMD dates

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#416]
Sorting by date is incorrect when dates with year precision are mixed with dates with month or day precision, or with date ranges.

(I stumbled across this when using a modified `chicago-author-date.csl` set up to sort the references section entries chronologically, but the effect is demonstrated just as clearly with the standard `chicago-author-date.csl` if all contributors are identical, as in the following example. ` type: article-newspaper` is merely used to have the complete dates appear in the bibliography output; same effect with other types, e.g., `book`.)

```
pandoc -F pandoc-citeproc -t plain  << EOT

# Text

Blah blah [@item1; @item2; @item3].

# References {-}

---
title: The Title
references:
- id: item1
  type: article-newspaper
  author:
  - family: Doe
    given: J.
  issued:
  - year: 2010
    month: 12
    day: 13
  title: The title
- id: item2
  type: article-newspaper
  author:
  - family: Doe
    given: J.
  issued:
  - year: 2007
    month: 12
    day: 12
  - year: 2007
    month: 12
    day: 13
  title: The title
- id: item3
  type: article-newspaper
  author:
  - family: Doe
    given: J.
  issued:
  - year: 2008
  title: The title
...

EOT
```

Actual output:

```
[...]


Doe, J. 2008. “The Title,” 2008.

———. 2010. “The Title,” December 13, 2010.

———. 2007. “The Title,” December 12–13, 2007.
```

Expected output:

```
[...]


Doe, J. 2007. “The Title,” December 12–13, 2007.

———. 2008. “The Title,” 2008.

———. 2010. “The Title,” December 13, 2010.

```
