### ISSUE TITLE
Only first citation processed from references

### ISSUE THREAD

**Issue by epogrebnyak** [jgm/pandoc-citeproc#417]
I'm processing several minimal citations, pandoc is showing just the first one and ignores the rest.

Anything can be doen to fix this bahaviour, maybe some minimal changes to cite.txt? Tried adding `type` field, but behaviour stayed the same.

cite.txt:

```
---
nocite: |
  @*
references:
- title: Will Digital Technologies Transform Agriculture in Developing Countries?
  publisher: World Bank
  URL: http://documents.worldbank.org/curated/en/481581468194054206/pdf/WPS7669.pdf
  
- title: How an innovative corn supply chain model can empower companies to help farmers
  URL: http://blogs.edf.org/growingreturns/2017/09/06/how-an-innovative-corn-supply-chain-model-can-empower-companies-to-help-farmers/
  
- title: Food Logistics From Farm to Fork
  URL: https://www.inboundlogistics.com/cms/article/food-logistics-from-farm-to-fork/
...
```
 
```
pandoc -F pandoc-citepro cite.txt 
λ pandoc -F pandoc-citeproc cite.txt
<div id="refs" class="references">
<div id="ref-">
<p>“Will Digital Technologies Transform Agriculture in Developing Countries?” n.d. World Bank. <a href="http://documents.worldbank.org/curated/en/481581468194054206/pdf/WPS7669.pdf" class="uri">http://documents.worldbank.org/curated/en/481581468194054206/pdf/WPS7669.pdf</a>.</p>
</div>
</div>

```
