### ISSUE TITLE
Book title casing changed

### ISSUE THREAD

**Issue by qaisjp** [jgm/pandoc-citeproc#436]
Input `.bib`:

```bibtex
@Book{P2,
  author     = "Chen-Chung Chang and H. Jerome Keisler",
  title      = "Model Theory",
  publisher  = "North-Holland",
  edition   = {Third},
  year       = 1990,
}
```

Output `.yaml`:

```yaml
---
references:
- id: P2
  type: book
  author:
  - family: Chang
    given: Chen-Chung
  - family: Keisler
    given: H. Jerome
  issued:
  - year: 1990
  title: Model theory
  publisher: North-Holland
  edition: Third
...
```
