### ISSUE TITLE
Call pandoc-citeproc filter from YAML metadata block instead of commandline?

### ISSUE THREAD

**Issue by AquaL1te** [jgm/pandoc-citeproc#440]
Below is a snippet from my YAML metadata block.

```yaml
---
title: Test case
date: \today
lang: en-US
papersize: a4
documentclass: IEEEtran
classoption: twocolumn
cite-method: citeproc
bibliography: bibliography.bib
filters: pandoc-citeproc
reference-section-title: References
link-citations: True
numbersections: True
toc: False
---
```

As you can see I've set `filters: pandoc-citeproc`, which is also shown in [this](https://pandoc.org/MANUAL.html#default-files) YAML metadata block example. However, it doesn't seem to work. It only works when I provide `--filter pandoc-citeproc` on the commandline. This is a bit confusing, can pandoc-citeproc be called from the metadata, or not? If it can be, what am I doing wrong?

Using Fedora 31 with:
pandoc-citeproc-common-0.15.0.1-1.fc31.noarch
pandoc-pdf-2.5-1.fc31.x86_64
pandoc-common-2.5-1.fc31.noarch
pandoc-2.5-1.fc31.x86_64
pandoc-citeproc-0.15.0.1-1.fc31.x86_64
