### ISSUE TITLE
chicago-fullnote-bibliography, "speech": Extra comma after title

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#45]
Using chicago-fullnote-bibliography, "speech" items are rendered with an extra comma after the title in the notes (in the bibliography, they look ok). – Zotero, using the very same csl style, does not insert a comma. – Any idea what's going on here?

Example, content from CMoS, 16e, 14.226:

```
pandoc -s -F pandoc-citeproc -t plain <<EOT

Foo [@item1]. Bar [@item2].

# References {-}

---
csl: chicago-fullnote-bibliography.csl
references:
- title-short: Early violent death in delinquent youth
  author:
  - family: Teplin
    given: Linda A.
  - family: McClelland
    given: Gary M.
  - family: Abram
    given: Karen M.
  - family: Washburn
    given: Jason J.
  id: item2
  issued:
    date-parts:
    - - 2005
      - 3
  title: 'Early violent death in delinquent youth: A prospective longitudinal study'
  type: speech
  genre: paper
  event: Annual Meeting of the American Psychology-Law Society
  event-place: La Jolla, CA

- author:
  - family: "D’Erasmo"
    given: Stacy
  id: item1
  issued:
    date-parts:
    - - 2000
      - 4
      - 26
  title: The craft and career of writing
  type: speech
  genre: lecture
  event-place: Northwestern University, Evanston, IL
...
EOT
```

Output:

```
Foo.[^1] Bar.[^2]

References {#references .unnumbered}
==========

D’Erasmo, Stacy. “The Craft and Career of Writing.” Lecture,
Northwestern University, Evanston, IL, April 26, 2000.

Teplin, Linda A., Gary M. McClelland, Karen M. Abram, and Jason J.
Washburn. “Early Violent Death in Delinquent Youth: A Prospective
Longitudinal Study.” Paper presented at the Annual Meeting of the
American Psychology-Law Society, La Jolla, CA, March 2005.

[^1]: Stacy D’Erasmo, “The Craft and Career of Writing,” (lecture,
    Northwestern University, Evanston, IL, April 26, 2000).

[^2]: Linda A. Teplin et al., “Early Violent Death in Delinquent Youth:
    A Prospective Longitudinal Study,” (paper presented at the Annual
    Meeting of the American Psychology-Law Society, La Jolla, CA, March
    2005).
```

Expected:

```
[^1]: Stacy D’Erasmo, “The Craft and Career of Writing” (lecture,
    Northwestern University, Evanston, IL, April 26, 2000).

[^2]: Linda A. Teplin et al., “Early Violent Death in Delinquent Youth:
    A Prospective Longitudinal Study” (paper presented at the Annual
    Meeting of the American Psychology-Law Society, La Jolla, CA, March
    2005).
```
