### ISSUE TITLE
Field value ignored when "raw" date type is used with CSL-YAML

### ISSUE THREAD

**Issue by mjfs** [jgm/pandoc-citeproc#468]
When using CSL-YAML the following record with date field works as expected:

```yaml
---
references:
- id: agenda
  title: "Meeting agenda"
  author:
  - literal: "Institution XYZ"
  issued: [[2020,2,11]]
...
```

However, when trying to use the "raw" date format, the value of "issued" segment is ignored:

```yaml
---
references:
- id: agenda
  title: "Meeting agenda"
  author:
  - literal: "Institution XYZ"
  issued:
  - raw: "2020-2-11"
...
```

If my understanding is correct the case above should work in the same way as it does in CSL-JSON, e.g.:

```json
"issued": {
     "raw": "2020-2-11"
}
```
