### ISSUE TITLE
Extra round brackets around empty issue/number (caused by year range?) 

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#51]
… seen when using chicago-author-date.csl (not in chicago-fullnote-bibliography.csl, modern-language-association.csl, or apa.csl). Can't be tested in Zotero, which does not allow date ranges.

Is there anything that would cause the processor to see a nonempty month in the "Doe" example?

Example:

```
pandoc -F pandoc-citeproc -t markdown-citations << EOT

@item1; @item2

---
csl: 
references:
- volume: 3
  page: '12-34'
  container-title: Journal of Something
  author:
  - family: Doe
    given: John
  id: item1
  issued:
    date-parts:
    - - 1987
    - - 1988
  title: The title
  type: article-journal
- volume: 4
  page: '12-34'
  container-title: Journal of Something
  author:
  - family: Roe
    given: Ron
  id: item2
  issued:
    date-parts:
    - - 1987
  title: The title
  type: article-journal
...
EOT
```
