### ISSUE TITLE
Disambiguation problems in styles with "ibid" and "ibid-with-locator" set.

### ISSUE THREAD

**Issue by davepwsmith** [jgm/pandoc-citeproc#53]
I am finding that pandoc-citeproc seems to add arbitrary disambiguation where the "ibid" and "ibid-with-locator" variables are tested for in CSL. My style is set to disambiguate by year, and I'm getting (for example) (Melo Neto 2006b) where there is only one text by Melo Neto referenced - indeed only one text in the bibtex file. It seems to pick up the (Ibidem) as a different author and thus disambiguate. See below:

```
pandoc --filter=pandoc-citeproc --csl=diacritica.csl -t markdown-citations << EOT
 @a @a @b @b @a @a @b @b

 ---
 references:
 - title: Work A
   id: a
   issued:
     date-parts:
     - - 2000
   author:
   - given: John
     family: Doe
   type: book
 - title: Work B
   id: b
   issued:
     date-parts:
     - - 1990
   author:
   - given: Jane
     family: Roe
   type: book
 ...
 EOT
```

Output:

```
Doe, (2000a) (*Ibidem*) Roe, (1990b) (*Ibidem*) Doe, (2000a) (*Ibidem*)
Roe, (1990b) (*Ibidem*)

<div class="references">

Doe, John (2000a), *Work a*.

Roe, Jane (1990b), *Work b*.

</div>
```

Expected Output:

```
Doe, (2000) (*Ibidem*) Roe, (1990) (*Ibidem*) Doe, (2000) (*Ibidem*)
Roe, (1990) (*Ibidem*)

<div class="references">

Doe, John (2000), *Work a*.

Roe, Jane (1990), *Work b*.

</div>
```

[The style](https://dl.dropboxusercontent.com/u/157682/diacritica.csl) works fine with Zotero plugins for Libre Office and Word.
