### ISSUE TITLE
Formatting issues with bibliography entries for item in book with book author in chicago-fullnote-bibliography.csl 

### ISSUE THREAD

**Issue by bauchner** [jgm/pandoc-citeproc#54]
The bibliography entry for items in a book with a book author is missing a comma and a space before the inclusive page range and the word that follows the period after the page range should be capitalized. 

Here the JSON CSL formatted version of such an entry

	{
		"id": 375,
		"type": "chapter",
		"title": "Introduction: Georges Canguilhem's critique of medical reason",
		"container-title": "Writings on medicine",
		"publisher": "Fordham University Press",
		"publisher-place": "New York",
		"page": "1–24",
		"source": "Library of Congress ISBN",
		"event-place": "New York",
		"ISBN": "9780823234318",
		"call-number": "R723 .C36513 2012",
		"note": "biblatexdata[origdate=2002;origpub=Éditions du Seuil;origtitle=Écrits sur la médecine;origplace=Paris;origlang=French]",
		"container-author": [
			{
				"family": "Canguilhem",
				"given": "Georges"
			}
		],
		"translator": [
			{
				"family": "Geroulanos",
				"given": "Stefanos"
			},
			{
				"family": "Meyers",
				"given": "Todd"
			}
		],
		"author": [
			{
				"family": "Geroulanos",
				"given": "Stefanos"
			},
			{
				"family": "Meyers",
				"given": "Todd"
			}
		],
		"issued": {
			"date-parts": [
				[
					"2012"
				]
			]
		}
	}

and here it is formatted as a bibliography entry.

> Geroulanos, Stefanos, and Todd Meyers. “Introduction: Georges Canguilhem’s Critique of Medical Reason.” In *Writings on Medicine*, by Georges Canguilhem1–24. translated by Stefanos Geroulanos and Todd Meyers. New York: Fordham University Press, 2012.

The capitalization issue also happens when copying directly from Zotero, so that is most likely a CSL issue, which I'm about to report too.

**Comment by nickbart1980** [comment]
The capitalization issue (“T/translated …”) has been reported at https://github.com/citation-style-language/styles/issues/986 in June 2014. It appears a solution would require allowing text-case on cs:group, but the discussion seems to have stalled; https://github.com/citation-style-language/styles/issues/986 is still open. As it is, this is nothing that can be fixed on the pandoc-citeproc side.

I cannot reproduce the “comma-space” issue (see example below), so this issue (https://github.com/jgm/pandoc-citeproc/issues/54) could be closed now.

```
pandoc --filter pandoc-citeproc -t markdown-citations << EOT

Foo [@375].

---
csl: chicago-fullnote-bibliography.csl
references:
- id: 375
  type: chapter
  author:
  - family: Geroulanos
    given: Stefanos
  - family: Meyers
    given: Todd
  translator:
  - family: Geroulanos
    given: Stefanos
  - family: Meyers
    given: Todd
  container-author:
  - family: Canguilhem
    given: Georges
  issued:
  - year: 2012
  title: 'Introduction: Georges Canguilhem''s critique of medical reason'
  container-title: Writings on medicine
  publisher: Fordham University Press
  publisher-place: New York
  event-place: New York
  page: 1–24
  ISBN: 9780823234318
...
EOT
```

Output:

```
Foo.[^1]

<div id="refs" class="references">

<div id="ref-375">

Geroulanos, Stefanos, and Todd Meyers. “Introduction: Georges
Canguilhem's Critique of Medical Reason.” In *Writings on Medicine*, by
Georges Canguilhem, 1–24. translated by Stefanos Geroulanos and Todd
Meyers. New York: Fordham University Press, 2012.

</div>

</div>

[^1]: Stefanos Geroulanos and Todd Meyers, “Introduction: Georges
    Canguilhem's Critique of Medical Reason,” in *Writings on Medicine*,
    by Georges Canguilhem, trans. Stefanos Geroulanos and Todd Meyers
    (New York: Fordham University Press, 2012), 1–24.
```
