### ISSUE TITLE
<choose> inside <substitute>: unexpected output

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#58]
I have been trying to get chicago-author-date.csl to cope with unsigned articles and reviews, where the name of the newspaper or periodical needs to stand in place of the author (see CMoS 14.207 and 14.217).

Inserting a `<choose>` element into `<substitute>` in the macros `<macro name="contributors">` and `<macro name="contributors-short">` to have a nonexisting author replaced by the output of `<text macro="container-title"/>` in case the item is of one of the article types results in expected behaviour as far as these items themselves [@nyt; @ealz] are concerned. However, items where the _title_ substitutes a missing author [@stanze] are no longer rendered correctly (though [@stanze] is rendered correctly in pandoc using an unmodified chicago-author-date.csl, as it is in Zotero with the modified csl file. In addition, fbennett confirms that `<choose>` inside `<substitute>` should work; see https://forums.zotero.org/discussion/37961/choose-element-inside-substitute/#Item_0). 

I suspect a pandoc-citeproc bug here.

Example:

```
pandoc -F pandoc-citeproc -t markdown-citations << EOT

In these two items, the name of the newspaper or periodical needs to stand in place of the author (see CMoS 16e 14.207 and 14.217) [@nyt; @ealz].

In this item, the title replaces the (unknown) author (see 14.79) [@stanze, p. 12].

# References

---
csl: https://gist.githubusercontent.com/nickbart1980/6039e992a2e128f9314b/raw/b18500cc80b715cd02dfa7a82da7c0ed3690b2db/chicago-author-date-modif20140630.csl
references:
- type: article-journal
  id: ealz
  title: Unsigned review of *Geschichten der romanischen und germanischen Völker*, by Leopold von Ranke
  issued:
    date-parts:
    - - 1828
      - 02
  container-title: Ergänzungsblätter zur Allgemeinen Literatur-Zeitung
  issue: 23–24
  language: de-DE

- type: article-newspaper
  id: nyt
  title: In Texas, ad heats up race for governor
  issued:
    date-parts:
    - - 1998
      - 07
      - 30
  container-title: New York Times
  language: en-US

- type: book
  id: stanze
  title: Stanze in lode della donna brutta
  issued:
    date-parts:
    - - 1547
  publisher-place: Florence
  language: it-IT
...
EOT
```

Expected output:

```
In these two items, the name of the newspaper or periodical needs to
stand in place of the author (see CMoS 16e 14.207 and 14.217) (*New York
Times* 1998; *Ergänzungsblätter zur Allgemeinen Literatur-Zeitung*
1828).

In this item, the title replaces the (unknown) author (see 14.79) (*Stanze in 
lode della donna brutta* 1547, 12).

<div class="references">

References {#references .unnumbered}
==========

*Ergänzungsblätter zur Allgemeinen Literatur-Zeitung*. 1828. “Unsigned
review of *Geschichten der romanischen und germanischen Völker*, by
Leopold von Ranke,” no. 23–24 (February).

*New York Times*. 1998. “In Texas, Ad Heats Up Race for Governor,” July
30.

*Stanze in lode della donna brutta*. 1547. Florence.

</div>
```

Actual output:

```
In these two items, the name of the newspaper or periodical needs to
stand in place of the author (see CMoS 16e 14.207 and 14.217) (*New York
Times* 1998; *Ergänzungsblätter zur Allgemeinen Literatur-Zeitung*
1828).

In this item, the title replaces the (unknown) author (see 14.79) (1547,
12).

<div class="references">

References {#references .unnumbered}
==========

*Ergänzungsblätter zur Allgemeinen Literatur-Zeitung*. 1828. “Unsigned
review of *Geschichten der romanischen und germanischen Völker*, by
Leopold von Ranke,” no. 23–24 (February).

*New York Times*. 1998. “In Texas, Ad Heats up Race for Governor,” July
30.

1547\. *Stanze in lode della donna brutta*. Florence.

</div>
```

chicago-author-date-modif20140630.csl is at https://gist.github.com/nickbart1980/6039e992a2e128f9314b
