### ISSUE TITLE
Incorrect parsing of locator prefixes when using roman volume numbers

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#61]
The routines trying to parse locator prefixes such as "vol.", "pp.", "l.", "no." misfire when roman volume numbers are preceding (arabic) page numbers, as in `Foo [@doe, VIII, 89]`, and replace the roman volume numbers by unwanted "vol.", "no.", "l." etc. instead.

"MVIII" or "CL" as volume numbers even suppress locator output altogether.

Variations of this pattern are found frequently among the examples in the MHRA style guide (http://www.mhra.org.uk/Publications/Books/StyleGuide/StyleGuideV3_1.pdf).

Example: 

```
pandoc -s -F pandoc-citeproc -t markdown-citations << EOT

---
csl: modern-humanities-research-association.csl
references:
- author:
  - family: Doe
    given: John
  id: doe
  issued:
    date-parts:
    - - 1985
  title: Title
  type: book
  publisher: Publisher
- author:
  - family: Roe
    given: Rob
  id: roe
  issued:
    date-parts:
    - - 1985
  title: Title
  type: book
  publisher: Publisher
...

# Text

Foo [@doe, VIII, 89]

Foo [@roe, III, 89]

Foo [@doe, LVIII, 89]

Foo [@roe, MVIII, 89]

Foo [@doe, CL, 89]

# References

EOT
```

Actual output:

```
Text
====

Foo[^1]

Foo[^2]

Foo[^3]

Foo[^4]

Foo[^5]

<div class="references">

References {#references .unnumbered}
==========

Doe, John, *Title* (Publisher, 1985)

Roe, Rob, *Title* (Publisher, 1985)

</div>

[^1]: John Doe, *Title* (Publisher, 1985), vol. 89.

[^2]: Rob Roe, *Title* (Publisher, 1985), no. 89.

[^3]: Doe, l. 89.

[^4]: Roe.

[^5]: Doe.
```

Expected output:

```
Text
====

Foo[^1]

Foo[^2]

Foo[^3]

Foo[^4]

Foo[^5]

<div class="references">

References {#references .unnumbered}
==========

Doe, John, *Title* (Publisher, 1985)

Roe, Rob, *Title* (Publisher, 1985)

</div>

[^1]: John Doe, *Title* (Publisher, 1985), VIII, 89.

[^2]: Rob Roe, *Title* (Publisher, 1985), III, 89.

[^3]: Doe, LVIII, 89.

[^4]: Roe, MVIII, 89.

[^5]: Doe, CL, 89.
```
