### ISSUE TITLE
Incorrect disambiguation by (short) title using MHRA style

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#63]
Disambiguation by (short) title using `modern-humanities-research-association.csl` is not as expected:

Citing like in the following line, disambiguation in subsequent citations is as expected (i.e., last name plus short title):

`Foo [@doe1]. Bar [@doe2]. Foo [@doe1]. Bar [@doe2].`

Citing like in the following, when `@doe2` appears only once, the subsequent `@doe1` is rendered without disambiguation (i.e., just the last name):

`Foo [@doe1]. Bar [@doe2]. Foo [@doe1].`

The latter works as expected using Zotero with `modern-humanities-research-association.csl`. Interestingly enough, pandoc with `chicago-fullnote-bibliography.csl` also gives the expected output.

Example file at https://gist.github.com/njbart/76e01842bc1e5695d72c

**Comment by jgm** [comment]
Here's a test case
```
@item1

@item2

@item1

# References

---
references:

- id: item1
  type: webpage
  author:
  - family: Doe
    given: John
  title: Title
  container-title: The Web Site
  URL: http://www.example.com
  issued:
   date-parts:
    - - 2006
      - 10
      - 26

- id: item2
  type: webpage
  author:
  - family: Doe
    given: Sam
  title: Title
  container-title: The Web Site
  URL: http://www.example.com
  issued:
   date-parts:
    - - 2006
      - 10
      - 26
    - - 2006
      - 11
      - 27
...
```

This gives (plain output):

```
John Doe[1]

Sam Doe[2]

Doe[3]



REFERENCES


Doe, John, ‘Title’, _The Web Site_, 2006 <http://www.example.com>

Doe, Sam, ‘Title’, _The Web Site_, 2006 <http://www.example.com>

[1] ‘Title’, _The Web Site_, 2006 <http://www.example.com>.

[2] ‘Title’, _The Web Site_, 2006 <http://www.example.com>.

[3] 
```
Note also the empty note 3!
