### ISSUE TITLE
Date range within same year

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#7]
pandoc-citeproc throws an error when biblio data contain a date range within the same year:

```
pandoc --filter pandoc-citeproc -t markdown-citations <<EOT

@item1

---
references:
- title: Title
  id: item1
  issued:
  - day: 24
    month: 09
    year: 2011
  - day: 26
    month: 09
    year: 2011
  author:
    given:
    - Ann
    family: Author
  container-title: Journal
  type: article-journal
...

EOT
```

Result:

```
pandoc-citeproc: Prelude.init: empty list
pandoc: Error running filter pandoc-citeproc
```

Same effect with year-months only (e.g., 2011-08/2011-09).

pandoc-citeproc throws no such error in case all date components in ranges are identical, e.g. 2011/2011, 2011-08/2011-08, or 2011-08-23/2011-08-23. (Well-maintained data should not contain such ranges, but I wonder whether pandoc-citeproc could treat these as point dates, or report an error in such cases.)
