### ISSUE TITLE
Allow abbreviation of a date range

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc-citeproc#73]
Styles that ask for abbreviated number ranges require the same rules to applied across a work, whereas in CSL they are currently only applied to page numbers. I have asked for this to be extended in the next version of the specification, as well as add some omitted range styles. In the meantime, however, it is not possible to write an abbreviated date range using Pandoc.

I do not believe that there would be any negative effects to applying page range formats to dates when using the '[chicago](http://citationstyles.org/downloads/specification.html#appendix-v-page-range-formats)' option, if you feel this would be an acceptable deviation from the specification. I wouldn't recommend it when using the 'minimal' or 'minimal-two' option, however, as there is a [common exception to this rule for dates](http://global.oup.com/uk/academic/authors/AuthorGuidelinesMain/HouseStyle/#lev21) to prevent things such as '1754–809'.

Another potential workaround produces some unexpected results:

```
pandoc -t plain -F pandoc-citeproc << EOT

---
references:
- event-place: Hereford
  publisher-place: Hereford
  collection-number: "27–29, 32, 34, 41, 42, 46, 51, 62, 67, 68"
  number-of-volumes: '10'
  call-number: DA670 .L69 R52 suppl.1 IMS
  first-reference-note-number: 1
  source: toroprod.library.utoronto.ca Library Catalog
  id: foster:1931registrum
  issued:
    date-parts:
    - - 1931
    - - 68
  title: The Registrum antiquissimum of the cathedral church of Lincoln
  type: book
  collection-title: Publications of the Lincoln Record Society
  publisher: Lincoln Record Society
  editor:
  - family: Foster
    given: C.W.
  - family: Major
    given: Kathleen

---

@foster:1931registrum

EOT
```

I was hoping for this:

```
Foster and Major (1931–68)

Foster, C.W., and Kathleen Major, eds. 1931–68. _The Registrum
Antiquissimum of the Cathedral Church of Lincoln_. 10 vols. Publications
of the Lincoln Record Society, 27–29, 32, 34, 41, 42, 46, 51, 62, 67,
68. Hereford: Lincoln Record Society.
```

Instead, one receives this:

```
Foster and Major (1931–68AD)

Foster, C.W., and Kathleen Major, eds. 1931–68AD. _The Registrum
Antiquissimum of the Cathedral Church of Lincoln_. 10 vols. Publications
of the Lincoln Record Society, 27–29, 32, 34, 41, 42, 46, 51, 62, 67,
68. Hereford: Lincoln Record Society.
```

(Separately, even if you judge it better to leave the date range problem with the CSL people, it should be 'AD 68' rather than '68AD' according to Chicago, though perhaps that's an issue in `chicago-author-date.csl`.)
