### ISSUE TITLE
Numbers interpreted differently from citeproc-js

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc-citeproc#74]
Pandoc-citeproc seems to interpret a the difference between a number and a string in a stricter manner than citeproc-js, which can cause some issues in odd circumstances. In `chicago-author-date.csl`, a collection title is displayed either with or without a comma, depending on whether the series number is detected to be a number:

``` xml
  <macro name="collection-title">
    <choose>
      <if match="none" type="article-journal">
        <choose>
          <if match="none" is-numeric="collection-number">
            <group delimiter=", ">
              <text variable="collection-title" text-case="title"/>
              <text variable="collection-number"/>
            </group>
          </if>
          <else>
            <group delimiter=" ">
              <text variable="collection-title" text-case="title"/>
              <text variable="collection-number"/>
            </group>
          </else>
        </choose>
      </if>
    </choose>
  </macro>
```

This doesn't work in pandoc-citeproc, however, with anything but a simple number:

```
pandoc -t plain -F pandoc-citeproc << EOT

---
references:
- event-place: Fakenham
  publisher-place: Fakenham
  collection-number: "2–3"
  call-number: BX2596 .N64 S7 1932 1-2 IMST
  first-reference-note-number: 1
  number-of-pages: '313'
  source: toroprod.library.utoronto.ca Library Catalog
  id: west:1932st
  issued:
    date-parts:
    - - 1932
  title: "St. Benet of Holme, 1020–1210"
  type: book
  collection-title: Norfolk Record Society
  publisher: Miller
  editor:
  - family: West
    given: J.R.
- event-place: Hereford
  publisher-place: Hereford
  collection-number: "27–29, 32, 34, 41, 42, 46, 51, 62, 67, 68"
  number-of-volumes: '10'
  call-number: DA670 .L69 R52 suppl.1 IMS
  first-reference-note-number: 1
  source: toroprod.library.utoronto.ca Library Catalog
  id: foster:1931registrum
  issued:
    date-parts:
    - - 1931
    - - 1968
  title: The Registrum antiquissimum of the cathedral church of Lincoln
  type: book
  collection-title: Publications of the Lincoln Record Society
  publisher: Lincoln Record Society
  editor:
  - family: Foster
    given: C.W.
  - family: Major
    given: Kathleen
- event-place: Leuven
  publisher-place: Leuven
  collection-number: 1st ser., studia 29
  ISBN: '9058670619'
  call-number: B738.D5 M49 2000
  title-short: Die Distinktionstechnik in der Kanonistik des 12. Jahrhunderts
  first-reference-note-number: 1
  number-of-pages: '363'
  language: German
  author:
  - family: Meyer
    given: Christoph H.F.
  source: Library of Congress ISBN
  id: meyer:2000distinktionstechnik
  issued:
    date-parts:
    - - 2000
  title: 'Die Distinktionstechnik in der Kanonistik des 12. Jahrhunderts: Ein Beitrag
    zur Wissenschaftsgeschichte des Hochmittelalters'
  type: book
  collection-title: Mediaevalia Lovaniensia
  publisher: Leuven University Press
...

@west:1932st; @foster:1931registrum; @meyer:2000distinktionstechnik

EOT
```
## Expected Output

As one receives with citeproc-js:

```
West (1932); Foster and Major (1931–1968); Meyer (2000)

Foster, C.W., and Kathleen Major, eds. 1931–1968. _The Registrum
Antiquissimum of the Cathedral Church of Lincoln_. 10 vols. Publications
of the Lincoln Record Society 27–29, 32, 34, 41, 42, 46, 51, 62, 67,
68. Hereford: Lincoln Record Society.

Meyer, Christoph H.F. 2000. _Die Distinktionstechnik in der Kanonistik
des 12. Jahrhunderts: Ein Beitrag zur Wissenschaftsgeschichte des
Hochmittelalters_. Mediaevalia Lovaniensia, 1st ser., studia 29. Leuven:
Leuven University Press.

West, J.R., ed. 1932. _St. Benet of Holme, 1020–1210_. Norfolk Record
Society 2–3. Fakenham: Miller.
```
## Actual Output

An unneeded comma is added to the citations for Foster and Major (1931–1968) and West (1932).

```
West (1932); Foster and Major (1931–1968); Meyer (2000)

Foster, C.W., and Kathleen Major, eds. 1931–1968. _The Registrum
Antiquissimum of the Cathedral Church of Lincoln_. 10 vols. Publications
of the Lincoln Record Society, 27–29, 32, 34, 41, 42, 46, 51, 62, 67,
68. Hereford: Lincoln Record Society.

Meyer, Christoph H.F. 2000. _Die Distinktionstechnik in der Kanonistik
des 12. Jahrhunderts: Ein Beitrag zur Wissenschaftsgeschichte des
Hochmittelalters_. Mediaevalia Lovaniensia, 1st ser., studia 29. Leuven:
Leuven University Press.

West, J.R., ed. 1932. _St. Benet of Holme, 1020–1210_. Norfolk Record
Society, 2–3. Fakenham: Miller.
```
