### ISSUE TITLE
Stopwords not capitalized after a colon

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc-citeproc#76]
As noted in #25, a stopword following a colon in a title is not capitalized:

```
pandoc -t plain -F pandoc-citeproc << EOT

---
references:
- title: 'foo bar baz: bazbaz bar foo'
  author:
  - given: Al
    family: Author
  issued:
    date-parts:
    - - 1998
  id: item1
  type: article-journal
- title: 'foo bar baz: the bazbaz bar foo'
  author:
  - given: Al
    family: Author
  issued:
    date-parts:
    - - 1998
  id: item2
  type: article-journal
- title: 'foo bar baz: a bazbaz bar foo'
  author:
  - given: Al
    family: Author
  issued:
    date-parts:
    - - 1998
  id: item3
  type: article-journal
- title: 'foo bar baz: an abazbaz bar foo'
  author:
  - given: Al
    family: Author
  issued:
    date-parts:
    - - 1998
  id: item4
  type: article-journal

---

@item1, @item2, @item3, @item4

EOT
```
## Expected Output

```
Author (1998a), Author (1998b), Author (1998c), Author (1998d)

Author, Al. 1998a. ‘Foo Bar Baz: Bazbaz Bar Foo’.

———. 1998b. ‘Foo Bar Baz: The Bazbaz Bar Foo’.

———. 1998c. ‘Foo Bar Baz: A Bazbaz Bar Foo’.

———. 1998d. ‘Foo Bar Baz: An Abazbaz Bar Foo’.
```
## Actual Output

```
Author (1998a), Author (1998b), Author (1998c), Author (1998d)

Author, Al. 1998a. ‘Foo Bar Baz: Bazbaz Bar Foo’.

———. 1998b. ‘Foo Bar Baz: the Bazbaz Bar Foo’.

———. 1998c. ‘Foo Bar Baz: a Bazbaz Bar Foo’.

———. 1998d. ‘Foo Bar Baz: an Abazbaz Bar Foo’.
```
