### ISSUE TITLE
Sequence of disambiguating year suffixes does not start with "a" for each author

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#8]
```
pandoc --filter pandoc-citeproc -t markdown-citations <<EOT

@item1, @item2, @item3, @item4

---
references:
- title: Title one
  id: item1
  issued:
    year: 2003
  author:
    given:
    - Al
    family: Author
  type: article-journal
  language: en-US
- title: Title two
  id: item2
  issued:
    year: 2003
  author:
    given:
    - Al
    family: Author
  type: article-journal
  language: en-US
- title: Title three
  id: item3
  issued:
    year: 2003
  author:
    given:
    - Al
    family: Buthor
  type: article-journal
  language: en-US
- title: Title four
  id: item4
  issued:
    year: 2003
  author:
    given:
    - Al
    family: Buthor
  type: article-journal
  language: en-US
...

EOT
```

Result:

```
Author (2003a), Author (2003b), Buthor (2003c), Buthor (2003d)

<div class="references">

Author, Al. 2003a. “Title One.”

———. 2003b. “Title Two.”

Buthor, Al. 2003c. “Title Three.”

———. 2003d. “Title Four.”

</div>
```

Correct output would be "Buthor (2003a), Buthor (2003b)".
