### ISSUE TITLE
en-dash as point locator's range delimiter outputs "p." instead of "pp."

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#84]
If a point locator's range delimiter as in `[@item1, pp. 12-13]` is a hyphen, output is as expected: "pp. 12–13". If it is an en-dash, or two consecutive hyphens, output is "p. 12–13", resp. "p. 12--13". 

Not entirely sure about the double hyphen, but at least the en-dash should be accepted as a range delimiter after "pp.".

Note that this effect is only seen with styles such as apa.csl which actually print "p." or "pp.".

Example:

```
pandoc -s -F pandoc-citeproc -t markdown-citations << EOT

---
csl: apa.csl
references:
- id: item1
  type: book
  author:
  - family: Doe
    given: John
  title: Title
  publisher: Publisher
  publisher-place: Place
  issued:
    date-parts:
    - - 2006
...

# (Author Year Locator)

hyphen: [@item1, pp. 12-13]

two hyphens: [@item1, pp. 12--13]

en-dash: [@item1, pp. 12–13]

# Author (Year Locator)

hyphen: @item1 [pp. 12-13]

two hyphens: @item1 [pp. 12--13]

en-dash: @item1 [pp. 12–13]

EOT
```
