### ISSUE TITLE
Date range: no space between month & day, no en-dash between months

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#87]
Using `chicago-author-date.csl`, date ranges in `webpage` items are rendered without spaces between month and day, and without en-dashes between months (the latter in `article-newspaper` items, too).

Since I'm spotting nothing obviously wrong with the CSL code, this might be a pandoc-citeproc issue:

Background: The current `chicago-author-date.csl` uses, for no apparent reason, two different bits of essentially equivalent code for rendering month-day combos. One however, gives the expected result, the other doesn't.

https://github.com/citation-style-language/styles/blob/master/chicago-author-date.csl#L422, used for article-newspaper etc.:

```
<macro name="day-month">
  <date variable="issued">
    <date-part name="month"/>
    <date-part name="day" prefix=" "/>
  </date>
</macro>
```

https://github.com/citation-style-language/styles/blob/master/chicago-author-date.csl#L155, used for webpage:

```
<date variable="issued" delimiter=" ">
  <date-part name="month"/>
  <date-part name="day"/>
</date>
```

Of course, a dedicated date-parts attribute `month-day` would be a much cleaner solution here but does not exist yet (currently, there is only `year-month-day`, `year-month`, and `year` (see http://citationstyles.org/downloads/specification.html#date). 

In particular, a date-parts attribute `month-day` would allow month-day combos in certain non-English locales to be rendered correctly. Introducing a date-parts attribute `month-day`, however, requires separating affixes from delimiters, at least for Chinese, and this in turn requires modifying the CSL schema, e.g., by introducing `cs:group` within `cs:date`. This has been discussed (see https://forums.zotero.org/discussion/7433/new-translatros-wished-for-faz-and-nzz/), but apparently no clear consensus has been reached yet.

Now, `chicago-author-date.csl`, as it is, correctly renders month-day combos in date ranges in `article-newspaper`, but not in `webpage`: spaces between month and day are missing. In addition, en-dashes between months are left out for both item types.

Example:

```
pandoc -F pandoc-citeproc -t markdown-citations << EOT

@item1 -- webpage, date

@item2 -- webpage, date range

@item2a -- webpage, date range YM

@item2b -- webpage, date range across years

@item3 -- article-newspaper

@item3b -- article-newspaper YM

# References

---
references:

- id: item1
  type: webpage
  author:
  - family: Doe
    given: John
  title: Title
  container-title: The Web Site
  URL: http://www.example.com
  issued:
   date-parts:
    - - 2006
      - 10
      - 26

- id: item2
  type: webpage
  author:
  - family: Doe
    given: John
  title: Title
  container-title: The Web Site
  URL: http://www.example.com
  issued:
   date-parts:
    - - 2006
      - 10
      - 26
    - - 2006
      - 11
      - 27

- id: item2a
  type: webpage
  author:
  - family: Doe
    given: John
  title: Title
  container-title: The Web Site
  URL: http://www.example.com
  issued:
   date-parts:
    - - 2006
      - 10
    - - 2006
      - 11

- id: item2b
  type: webpage
  author:
  - family: Doe
    given: John
  title: Title
  container-title: The Web Site
  URL: http://www.example.com
  issued:
   date-parts:
    - - 2006
      - 12
      - 31
    - - 2007
      - 01
      - 01

- id: item3
  type: article-newspaper
  author:
  - family: Doe
    given: John
  title: Title
  container-title: The Newspaper
  URL: http://www.example.com
  issued:
   date-parts:
    - - 2006
      - 10
      - 26
    - - 2006
      - 11
      - 27

- id: item3b
  type: article-newspaper
  author:
  - family: Doe
    given: John
  title: Title
  container-title: The Newspaper
  URL: http://www.example.com
  issued:
   date-parts:
    - - 2006
      - 10
    - - 2006
      - 11
...

EOT
```

Expected output:

```
Doe (2006c) -- webpage, date

Doe (2006d) -- webpage, date range

Doe (2006a) -- webpage, date range YM

Doe (2006–2007) -- webpage, date range across years

Doe (2006e) -- article-newspaper

Doe (2006b) -- article-newspaper YM

<div class="references">

References {#references .unnumbered}
==========

Doe, John. 2006a. “Title.” *The Web Site*. October–November.
<http://www.example.com>.

———. 2006b. “Title.” *The Newspaper*, October–November.
<http://www.example.com>.

———. 2006c. “Title.” *The Web Site*. October 26.
<http://www.example.com>.

———. 2006d. “Title.” *The Web Site*. October 26–November 27.
<http://www.example.com>.

———. 2006e. “Title.” *The Newspaper*, October 26–November 27.
<http://www.example.com>.

———. 2006–2007. “Title.” *The Web Site*. December 31–January 1.
<http://www.example.com>.

</div>
```

Actual output:

```
Doe (2006c) -- webpage, date

Doe (2006d) -- webpage, date range

Doe (2006a) -- webpage, date range YM

Doe (2006–2007) -- webpage, date range across years

Doe (2006e) -- article-newspaper

Doe (2006b) -- article-newspaper YM

<div class="references">

References {#references .unnumbered}
==========

Doe, John. 2006a. “Title.” *The Web Site*. OctoberNovember.
<http://www.example.com>.

———. 2006b. “Title.” *The Newspaper*, OctoberNovember.
<http://www.example.com>.

———. 2006c. “Title.” *The Web Site*. October 26.
<http://www.example.com>.

———. 2006d. “Title.” *The Web Site*. October26–November27.
<http://www.example.com>.

———. 2006e. “Title.” *The Newspaper*, October 26–November 27.
<http://www.example.com>.

———. 2006–2007. “Title.” *The Web Site*. December31–January1.
<http://www.example.com>.

</div>
```
