### ISSUE TITLE
Translator role missing when editor and translator are identical

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#9]
When editor and translator are identical, the translator role is not indicated:

```
pandoc --filter pandoc-citeproc -t markdown-citations <<EOT

@item1

---
references:
- title: "The title"
  id: item1
  issued:
    year: 2013
  author:
    given:
    - Al
    family: Author
  container-title: "The booktitle"
  editor:
    given:
    - Edward
    family: Editor
  translator:
    given:
    - Edward
    family: Editor
  type: chapter
...

EOT
```

Result:

```
Author (2013)

<div class="references">

Author, Al. 2013. “The Title.” In *The Booktitle*, edited by Edward
Editor.

</div>
```

Expected:

```
Author (2013)

<div class="references">

Author, Al. 2013. “The Title.” In *The Booktitle*, edited and translated by Edward
Editor.

</div>
```
