### ISSUE TITLE
<et-al font-style="italic"/> not honoured

### ISSUE THREAD

**Issue by nickbart1980** [jgm/pandoc-citeproc#91]
Using CSL styles with `<et-al font-style="italic"/>`, pandoc does not render the "*et al.*" part of in-text citations in italics.

See http://citationstyles.org/downloads/specification.html#et-al

Example:

````
pandoc -s -F pandoc-citeproc -t markdown-citations << EOT
---
csl: taylor-and-francis-harvard-x.csl
#csl: genetics.csl
#csl: oxford-studies-on-the-roman-economy.csl
references:
- id: article
  type: article-journal
  author:
  - family: Doe
    given: John F.
  - family: Moe
    given: John F.
  - family: Xoe
    given: John F.
  - family: Yoe
    given: John F.
  title: Articletitle
  container-title: Journaltitle
  issued:
    date-parts:
    - - 2006
...

# Text

@article

# References

EOT
````

Expected output:

````
Text
====

Doe *et al.* (2006)

<div class="references">

References {#references .unnumbered}
==========

Doe, J.F., Moe, J.F., Xoe, J.F., and Yoe, J.F., 2006. Articletitle.
*Journaltitle*.

</div>
````

Actual output:

````
Text
====

Doe et al. (2006)

<div class="references">

References {#references .unnumbered}
==========

Doe, J.F., Moe, J.F., Xoe, J.F., and Yoe, J.F., 2006. Articletitle.
*Journaltitle*.

</div>
````
