### ISSUE TITLE
letter casing inconsistency depending on bibliography source format

### ISSUE THREAD

**Issue by vehka** [jgm/pandoc-citeproc#92]
When creating a bibliography from a .bib file, pandoc-citeproc somehow lowercases all capitalized words in reference titles (except after a colon) when using the style "journal-of-the-royal-anthropological-institute.csl". The CSL file in itself seems to work, since letter case is correct when creating the bibliography from Zotero. Also, case is correct when using the YAML bibliography format.

So, this works ("New Order in Java" capitalized correctly):

```
pandoc --filter pandoc-citeproc -t markdown-citations <<EOT

Foo [@item1].

---
csl: journal-of-the-royal-anthropological-institute.csl
references:
- shortTitle: Exemplary centre, administrative periphery
  author:
  - family: Antlöv
    given: Hans
  source: Google Scholar
  id: item1
  issued:
    date-parts:
    - - '1995'
  title: ! 'Exemplary centre, administrative periphery: rural leadership and the New
    Order in Java'
  type: book
  publisher: Curzon Press

...
EOT
```

Output:

```
Foo (Antlöv 1995).

<div class="references">

<span style="font-variant:small-caps;">Antlöv, H.</span> 1995.
*Exemplary centre, administrative periphery: rural leadership and the
New Order in Java*. Curzon Press.

</div>
```

But this doesn't ("new order in java" in lower case):

```
pandoc --filter pandoc-citeproc -t markdown-citations --bibliography=/home/hwileniu/test.bib <<EOT

Foo [@antlov1995].

---
csl: journal-of-the-royal-anthropological-institute.csl
...
EOT
```

Output

```
Foo (Antlöv 1995).

<div class="references">

<span style="font-variant:small-caps;">Antlöv, H.</span> 1995.
*Exemplary centre, administrative periphery: Rural leadership and the
new order in java*. Curzon Press.

</div>
```

I'm using pandoc 1.13.1 & pandoc-citeproc 0.6.
- the csl file: https://www.dropbox.com/s/rzep85wt39luo5i/journal-of-the-royal-anthropological-institute.csl
- contents of the .bib file:

```
@book{antlov1995,
    title = {Exemplary centre, administrative periphery: rural leadership and the New Order in Java},
    shorttitle = {Exemplary centre, administrative periphery},
    publisher = {Curzon Press},
    author = {Antlöv, Hans},
    year = {1995},
}
```
