### ISSUE TITLE
bibtex @mastersthesis is not handled correctly

### ISSUE THREAD

**Issue by fibsifan** [jgm/pandoc-citeproc#98]
I use pandoc-citeproc to convert BibTeX to YAML (`pandoc-citeproc -y refs.bib > refs.yaml`) and afterwards I put the `refs.yaml` in the list of pandoc input files. When I have a `@mastersthesis` reference in my bibliography, it gets converted as follows:

```
@mastersthesis{Mustermann:1998,
  type = {Diplomarbeit},
  author = {Max Mustermann},
  title = {{Max Mustermanns Diplomarbeit}},
  school = {Musteruniversität Musterstadt},
  year = {1998},
}
```

becomes

```yaml
---
references:
- author:
  - family: Mustermann
    given: Max
  id: Mustermann:1998
  issued:
    date-parts:
    - - 1998
  title: Max Mustermanns Diplomarbeit
  type: thesis
  genre: "Master’s thesis"
  publisher: "Musteruniversität Musterstadt"
...
```
I would rather have "Diplomarbeit" in the genre field, as that seems to be the one, that gets printed. How can this be fixed, without having to correct every entry in the yaml file (is this a pandoc-citeproc issue at all)?
